### ISSUE TITLE
LAB TEST mesh network

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#1]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Create a functional lab network for the mesh

## To Do

- [x] Get SECTOR/CPE from Pedro
- [x] ESPRESSO in lab
- [x] RouterX in lab
- [x] Use L2TP instead of WIREGUARD for exit
- [x] Configure LAP/LOCO 
- [x] Config network model
- [x] Confirm functionality
