### ISSUE TITLE
Distributed Flash Party

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#105]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**
❌ **Blocked by:** 
👈**Depends on:**

The goal of this ticket is to get members familiar with hardware by preparing the hardware for deployment by distributing hardware that will be used on the super nodes, and providing a platform to support the configuration and testing of the hardware.

## To Do

- [ ] Decide if this will be done before this round of deployment 
- [ ] Gage interest from group
- [ ] Group hardware in logical bundles
- [ ] Figure out logistics
- [ ] Find a date/time to virtually connect.

**Comment by darkdrgn2k** [comment]
If you are interesting in participating please let it be known!

**Comment by infectedroot** [comment]
Interested in participating/contributing. If I may suggest, maybe we can add a couple of tasks between _Group hardware in logical bundles_ and _Figure out logistics_...

**Develop documentation/material for logical bundles** 
Is there some material that we can give participants ahead of time so they know what to buy based on the logical bundles?
I think a "Quick Start" guide that highlights items like: What do you need? How much will it cost? Where can I find instructions to put this together? What next? might go a long way so people know what they're getting into.


**Document Running Your Own Flash Party / Blog post about our install party**
If we're doing our own flash party... what's stopping us from letting others know how we did it? Maybe we should make a doc about how to roll your own flash party?

Maybe this might just come as a "blog post" on our website, so if there are others that want to emulate what we did, they have something to go by.

I think it might be a valuable asset to our Community Organizers if they were provided with something they can take and make their own.


Let me know if I'm completely off-base here...

**Comment by darkdrgn2k** [comment]
So the idea would be a co-working session of some sort. I'm not 100% sure how this whole thing would look in general. I think as we figure it out we can do documentation and/or write up. It could be a strong marketing piece.

Right now i have left the tasks very general, feel free to add/modify/change or just suggest tasks to add to this. 

My first task is to Gage interest, The level of interest will gauge how this will move forward. 
I will flag that there is limited time if we wish to do it before the super node deployments, but that does not mean we cant defer this till after some how if the interest is large enough!

**Reproducibility:**
We throw around the idea of doing workshops like this at TPL were its Learn By Doing on real gear. So this could be a valuable learning opportunity on how a workshop like that could work.

**Documentation:**
There are some key pieces already in the pipeline to be documented, but still rough. This may double as a means to smooth out the documentation.

**Format**
I'm thinking this would be some sort of virtual co-learning session. Like the virtual mesh nights, maybe video call, maybe a mix maybe as needed.

Since the super node itself will be using internet as an overlay network, the end product of this will be that all the pieces would actually be "live" over the installer's own internet connection and a functioning network! This way connectivity can also be tested and confirmed. We will MESH over the internet just like the super node would


Maybe @benhylau has some insight into the flash parties of dweb and how we can translate this to virtual.

I think because this is virtual some primers may be necessary. IE how to change the IP address of your computer. don't know

**Comment by darkdrgn2k** [comment]
Wont do in 2021
