### ISSUE TITLE
Supenode 4 - Lawrance

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#111]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:**
🎯 **Success criteria:** Deploy Super Node

Deploy super node along side Cisco

4000 Lawrence
![image](https://user-images.githubusercontent.com/29005789/109156103-759f8b80-773e-11eb-8791-4e28cf690175.png)

## To Do

- [x] Design Super Node
- [x] Pay for Super Node
- [x] Deploy Super Node -  #131 
- [x] Update node list - [PR](https://github.com/tomeshnet/node-list/pull/62)
- [x] Add to docs repo
- [x] Confirm connectivity and internet access

**Comment by darkdrgn2k** [comment]
Internet Source (3434 Ellington Av) lost power. Waiting for building to restore.

**Comment by TimTor** [comment]
A job well done.
