### ISSUE TITLE
Typical Supernode Deployment Setup

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#113]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**
❌ **Blocked by:** 
👈 **Depends on:**

Define typical super node setup and gear

## To Do

- [ ] Define super node setup 
- [ ] Create estimate on budgets
- [ ] Migrate to documents

**Comment by darkdrgn2k** [comment]
# Typical Simple Node

## Requirements
- For a typical Square building 
- Two mounts, one on each corner
- Inside location to store Router
- Power available

## Basic Gear
- Indoor case - $ ????
- EdgeRouter X SFP  - $100.00
- 2x Mounts - $200 Each $400 Total
- 8x Cinder blocks - $10 Each $80.00
- 4x LAP-GPS - $140 Each $560 Total
- 1/2 Box of Ubiquity ToughCable Pro $180 Each $90

## Backhaul

- Rooftop internet access (ie woolner) 
- Short Range P2P link ~NBE 140 (x2 one for other end)
- Mid Range P2P link ~PBE 180 (x2 one for other end)
- Long Distance Back-haul ~ $1000.00

**Comment by Pedro-on-a-bike** [comment]
Would add in:

**Recommended Gear**

- 3x Outdoor Enclosure - $ 75ea - $225 Total
- 3x EdgeRouter X SFP - $ 100ea - $300 Total
- 3x Non-penetrating Mounts - $200ea - $600 Total
- 12x Cinder blocks - $10ea - $120.00 Total
- 6x LAP-GPS - $140ea - $840 Total
- Box of Ubiquity ToughCable Pro $180 Total (depends on size of roof)
- Hardware $100
Grand Total: ~$2,400

The design intent is to be able to saturate a 1Gbps uplink to a supernode. With 20Mhz channels and 20 active users per antenna, this would give a supernode a capacity of 120 simultaneous users, with a 3:1 oversubscription ratio and a target of 25Mbps. 3 non-penetrating roof mounts will allow for a triangulated setup to provide 360 degree coverage.

**Comment by Pedro-on-a-bike** [comment]
Update:

Potential Gear Setup for an Ideal SuperNode:

**Assuming a Access Point Hub at the 4 edges of a building**
4x mount: $200 ea, $800 Total
16x cinder blocks: $10 ea, $160 Total
4x codebord: $50 ea, $200 Total
16x LAP-GPS: $130 ea, $2080 Total
4x Edgepoint R6 (PoE Injector/Switch): $160 ea, $640 Total

**For the Gateway/Backhaul**
1x outdoor rated enclosure: $200 ea, $200 Total
1x Qotom mini PC, Intel 8250u, 8 Port NIC: $750 ea, $750 Total
2x SFP to RJ45 Converters (2x GPON internet service): $40 ea, $80 Total
1x Box of Ubiquity ToughCable: Pro $180 ea, $180 Total
Misc Hardware: $200

This total comes to $5,100 pre-tax, $5,800 after tax

With 16x LAP-GPS, assuming 20 clients per Access Point, this should be able to service 320 clients total around the SuperNode. 16x LAP-GPS at 20Mhz channels would allow for approx 2,200 Mbps of aggregate bandwidth. To supply a backhaul for this setup, though it is not dedicated fiber, it would be recommended to have at least 2x business rated GPON fiber connections. An example of this would be Bell's 1Gbps Business Fiber.

**Estimated Max Power Consumption**
16x LAP-GPS: 7w ea, 112w Total
4x Edgepoint R6: 7w ea, 28w Total
1x Qotom Mini PC, 40w ea, 40w Total
2x SFP to RJ45: 1.7w ea, 3.4w Total

Total max power consumption: 183w. Assuming 24/7/31 at 15c/KWh, the Monthly max electrical cost would be approx. $20.50

It should be noted that this is a max calculation and actual power consumption should be lower.

**Operating Cost for SuperNode**
2x 1Gbps Business FIber: $130, $260 Total
1x Electrical Bill: $20.50
Total Monthly Operating Cost (Excluding roof top lease): $281, approx $320 after tax

**Some Points of Consideration**
Still need to determine if the Qotom Mini PC would have enough compute power to saturate 2x fiber GPON connections using WireGuard to allow for encrypted tunnels back to the datacenter. However it should be also noted that since we are only using 2x Business fiber and not dedicated fiber, it should not be expected that we will achieve 2Gbps saturation all the time. 

The closest comparison I could find are these routers:
https://teklager.se/en/products/routers/

Intel Core i7 4500U, which has a CPU Benchmark of 2541 and can do OpenVPN: 700Mbps, WG at 1Gbps
Intel Core i7 5550U, which has a CPU Benchmark of 2908 and can do OpenVPN: 800Mbps, WG at 1Gbps.
Intel Core i7 7500U, which has a CPU Benchmark of 3664 and can do OpenVPN: 1Gbps, WG at 1Gbps.

The Qotom linked below utilize the Intel Core i7 8550U, which has a CPU Benchmark of 5963, however OpenVPN and WG performance will need to be determined. It should also be noted that the single thread performance between the 7500u and 8550u are similar, however the 8550u excels greatly at multi-threading as it has an additional 2core/4threads.

More info on the Qotom 8550u MiniPC can be found here:
https://www.aliexpress.com/item/1005001429850294.html

and alternative is Yanling 8550u MiniPC:
https://www.aliexpress.com/item/1005002034409771.html
