### ISSUE TITLE
Supernode 5 - Albion

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#119]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** 11/27/2020
🎯 **Success criteria:** Ready to deploy suepernode
❌ **Blocked by:** 
👈 **Depends on:**

Albion cluster has been opened up for deployment.

234 Albion Rd
236 Albion Rd (GW)
238 Albion Rd

## To Do

- [ ] Map out out the area
  - Sector Antennas placement
  - Are P2P antennas are needed? If so where
- [x] Create JSON file for prospect nodes
- [x] Create hardware list
- [x] Create approval for hardware purchases (if necessary)
- [x] Order and receive hardware (if necessary)
- [x] Configure hardware
- [ ] Deploy hardware

**Comment by benhylau** [comment]
This is the node that needs to be designed and @Pedro-on-a-bike will send out invites for participation right?

**Comment by Pedro-on-a-bike** [comment]
Yes

**Comment by Pedro-on-a-bike** [comment]
**Hardware Requirements:** 
-(4) LAP-Lite-AP120
-(2) NanoBeam 5AC
-(2) ERX-SFP
-(1) Additional Cisco Mount
-Outdoor Ethernet Cable and hardware connectors

**Hardware Placement:** 
-No Hardware to be placed on 238 Albion Rd, North most building as it shorter than the other two buildings and faces directly into a golf course.
-236 Albion Rd will house the main ERX-SFP as it has direct access to the Gateway connection(Bell Fibe Internet). One LAP-Lite-AP120 will be placed on the north side of the building facing north (LAP0), assuming that Cisco is placing a mount here to provide Canopy Access to 238 Albion. Another LAP-Lite-AP120 will be placed on the south side of the building facing west (LAP1), assuming cisco is placing a mount here to provide Canopy Access to 234 Albion. A NanoBeam 5AC (NB0) should also be placed here to provide a PtP link to 234 Albion, assuming Cisco is also doing the same.
-234 Albion will also have a secondary ERX-SFP to power two more LAP-Lite-AP120 and a NanoBeam 5AC. A NanoBeam 5AC (NB1) will be placed on the north side of the building to complete the PtP link, assuming Cisco places their mount here. An additional mount of our own will need be placed on the east side of the building as it is most likely that Cisco will not have their own mount here. At this location, we will place two more LAP-Lite-AP120 facing east (LAP2) and south (LAP3) to complete 360 degree coverage of the surrounding area.

Another alternative is that we may be able to place the East Facing LAP2 from 234 Albion onto the south mount at 236 Albion that houses our west facing LAP1 and NB0. The benefit of this is to reduce load demands on the PtP bridge and to minimize outages since the gateway is located at 236 Albion. The potential issue with this is real estate as this mount will already house many other antennas, including Cisco's Canopy equipment.

![AlbionDeploy1](https://user-images.githubusercontent.com/27825513/100280053-908f1380-2f35-11eb-968d-f3c272a1b6aa.png)
![AlbionDeploy2](https://user-images.githubusercontent.com/27825513/100280054-9127aa00-2f35-11eb-8e69-5e99faba97af.png)

**Comment by Pedro-on-a-bike** [comment]
Albion update can be found here:

https://github.com/Pedro-on-a-bike/tomeshnet-node-list-albion/blob/main/tomeshnet-node-list

**Comment by darkdrgn2k** [comment]
Notified today that this building is no longer in the digital cannopy project.

**Comment by darkdrgn2k** [comment]
Wont do
