### ISSUE TITLE
Add coverage map to tomesh.net 

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#13]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** PR accepted
...

## To Do

- [x] Add support to draw coverage ARCs on tomesh.net site
- [x] Correct eslint errors
- [x] Accept PR https://github.com/tomeshnet/tomesh.net/pull/275
- [x] Create new node list (possibly related to #8)

**Comment by darkdrgn2k** [comment]
Map is now live!
