### ISSUE TITLE
Deployment - SN4

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#131]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**  Nodes are up and running and ready to receive connections
❌ **Blocked by:** 
👈 **Depends on:**

COVID NOTICE: If you will be attend please bring a mask or face covering.
We will be deploying along side the Digital Canopy Project on the following days

02-24-2021 -  Wed 9:00 am - 4000 Lawrence

## Weather
Weather outlook below take on 2/20/2021. Weather changes so check more updated forecast.
![image](https://user-images.githubusercontent.com/29005789/108600325-9a71b880-7364-11eb-94e7-349ad05c2f48.png)

## Bring With You

- Mask
   - Weather gear
     - Sun Glasses
     - Hat
     - Gloves
     - Warm Coat
- Laptop (charged)
- Phone (charged)
- Food/Water/Whatever else you need for the day

## Gear List

- [x] Boxes of cable (garage)
- [x] Pre-configured Hardware  (garage)
- [x] UV resistant Zip Ties
- [x] Saftey gear bucket x2 (y)
- [x] RJ45 connectors
    - [x] RJ45 Ends (Passthrough) (y)
    - [x] Rj45 Ends (Cartridge) (y)
- [x] Short Network Cables
    - [x] 3ft cat5e cables x10 (y)
    - [x] 1ft cat5e cables x10 (y)
    - [x] Short SFP DAC cable (y)
- [x] Tomesh stickers (y)
- [x] Extra hose clamps (y)
- [x] E-tape (y)
- [x] Walkie Talkies x3 (y)
- Tools
  - [x] Channel Lock (y)
  - [x] Socket Set (y)
  - [x] Pass through Crimper
  - [x] Standard Crimper
  - [x] Wire Cutters
  - [x] Line Testers
- [x] Mounts
- [x] Cinder Blocks
- [x] code board

**Comment by Pedro-on-a-bike** [comment]
Just wanted to add some additional info regarding the airfiber ptp link:

The heading from Thorncliff is 63 degrees with a tilt of 0. Thorncliff is approximately 75m above the ground.

The heading from Cougar is 244 degrees with a tilt of -0.13. Cougar is approximately 60m above the ground.

I will also add some pictures
AirFiber Link
![airlink_thorn_cougar](https://user-images.githubusercontent.com/27825513/108899312-4970f700-75e6-11eb-8780-37d67c7e4c2f.png)
View at Thorncliff
![View_at_thorn](https://user-images.githubusercontent.com/27825513/108899315-4a098d80-75e6-11eb-9177-d2cea6159e82.png)
View at Cougar
![View_at_cougar](https://user-images.githubusercontent.com/27825513/108899318-4a098d80-75e6-11eb-9fc9-4109dcca7980.png)
