### ISSUE TITLE
Schedule Canopy Install

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#136]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Schedule installs for all roofs required to finish canopy deployment.
❌ **Blocked by:** 
👈 **Depends on:**

## To Do

- [x] Confirm installs will need independent schedules
- [x] Establish Contact CoT
- [ ] Schedule buildings
  - ~236 Albion Rd (GW) #119~
  - ~238 Albion Rd #119~
  - [ ] 25 Cougar Court (GW) #64
  - [ ] 3434 Ellington Ave (GW) #63
  - [ ] 47 Thorncliffe Pk   #62
  - [ ] 53 Thorncliffe Pk (GW)  #61
  - [ ] 4000 Lawrence (Hardware Replacement) - #137

**Comment by darkdrgn2k** [comment]
This leg of the Digital Canopy deployment during covid along side cisco has come to an end.
