### ISSUE TITLE
Register tomesh phone number

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#14]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #7
📅 **Due date:** N/A  
🎯 **Success criteria:** Setup phone number

...

## To Do

- [x] Register phone number
- [x] Decide where voicemail should go (new email or existing)
- [x] Configure voicemail to email
- [x] Migrate to ownership of TOMESH
