### ISSUE TITLE
Establish Free Geek Relationship As Host

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#2]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** 6/23/2020
🎯 **Success criteria:** Create relationship with Free Geek, submit ISOC grant, complete all admin tasks to be able to access funds.

...

## To Do
- [x] Get Free Geek's board to approve on project
   - [x] Arrange meeting
   - [x] Get result/vote
- [x] Apply for ISOC #13
- [x] Receive ISOC Grant #13
- [x] Administration and Paperwork ([tasks](https://github.com/tomeshnet/mesh-deployment/issues/2#issuecomment-648465767))

**Comment by TimTor** [comment]
Advanced task completion with check mark on "Received ISOC grant" as the agreement has been executed and the invoicing procedure is underway for the 1st installment.

**Comment by benhylau** [comment]
## Free Geek Toronto <> Toronto Mesh Meeting Notes
- expense process
    - reimbursement with receipt
    - less preferred for liability reasons, requisition, but possible
        - name, name of company, item, confirmation that item is in stock
- reports
    - tomesh will write them, @TimTor to email to @ryan-fgt to send as PDF
    - first one due end-September
    - number of volunteers joining the project, photo of first supernode
- keep track of stock
- keep track of purchases
- publicity
    - **Free Geek Toronto**, FGT in short, is a **partner**, **collaborator**, **supporter**
    - email @ryan-fgt first before communication goes out
    - @ryan-fgt to send one-liner and logos
- FGT open to future fiscal hosting and other forms of collab
- landlord http://www.stclares.ca/properties/
