### ISSUE TITLE
Research tomesh AS 

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#20]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Get or Reject a tomesh AS  

# Summary
## ARIN
To gain ownership of an IPv4 or IPv6 Public Internet IP Space you must register with a Regional Internet Registry.  The North America registry is called [ARIN](arin.net). Once registered we can apply for a IP address size for both IPv4 and IPv6. 

## AS number
When applying for a IP range we will also be given an AS number.  This AS number is used to announce the location of these IP addresses to the internet.

# Reasons for requiring an AS 

## Multiple Exit Nodes support
When using multiple exit nodes, the ability to announce the same IP address for each one will allow for more resilience on the mesh.  Just like outbound connections could use any exit node, inbound connections could also be routed through any exit node.

Possibly not as important when using NAT

## Public IP routing inside of mesh
With an assigned AS we can router the IPv4 addresses into our mesh. The means that members can be given a publicly routable IPv4 IP address that lives on the mesh and is reachable from the internet.

Additionally publicly routable IPv6 addresses could also be handed out inside the mesh to every user.

## TORIX Peering
To peer with TORIX you require your own IP range to announce. Torix is a "short cut" to  many of the larger organizations that have presence in Toronto. This shortcut would lower the dependence on our internet egress.

## Easier donate ask
IPv4 are a rare commodity and many transit contacts may not wish to donate theirs.  By being able to bring our own IPv4 addresses, it may be easier to ask for service since it would not require depleting their ipv4 pools.

## Puts on on the "MAP"

By owning an AS and an IP range we could be seen as more then a few hobbits and serious players in the "internet" game.

## To Do

- [x] Research Pricing with ARIN
- [ ] Decide on size and ips
- [x] Research who can hold it (tomesh, free geek)
  - [x] Approach Hypha to be the legal custodian
  - [ ] Get approval 
- [x] What is needed to apply

**Comment by benhylau** [comment]
@ASoTNetworks can you take this ticket since you're also working on https://github.com/hyphacoop/organizing/issues/329 on Hypha side?

**Comment by ASoTNetworks** [comment]
I have revived the quote from ARIN and have been updating the ticket here https://github.com/hyphacoop/organizing/issues/329 to keep it in one place.

**Comment by benhylau** [comment]
I guess the next steps are:

- wait for #2 to land and ISOC grant to arrive at FreeGeek
- @tomeshnet/organizational-and-program-governance and @tomeshnet/project-operations to confirm we are good with this arrangement, and approve the budget
- @hyphacoop to place the order then invoice FreeGeek

cc. @TimTor @ryan-fgt

**Comment by benhylau** [comment]
@dasanchez maybe once we set up open collective you can be our first contributor :)

**Comment by darkdrgn2k** [comment]
Transfer of resource:

Source: https://www.arin.net/resources/fees/fee_schedule/

> ARIN will collect a $300 USD, non-refundable transfer processing fee for each transfer request of registration rights to Internet number resources

> This transfer processing fee will be invoiced to the source organization’s billing Point of Contact (POC) and are to be paid before evaluation of the transfer request begins. This fee does not guarantee approval of a transfer request.

Source: https://www.arin.net/resources/registry/transfers/quickguide/

> ARIN will collect a $300 USD, non-refundable processing fee for each transfer request of Internet number resources. This fee will be invoiced to the source organization’s billing Point of Contact (POC), is to be paid before request evaluation begins, and does not guarantee approval.

> Once the transfer is approved and ARIN receives a signed Registration Services Agreement (RSA) and any other applicable fees, and completes any required Inter-RIR coordination, your resources will be transferred.
