### ISSUE TITLE
Routing Hardware - ROUTER-X

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#22]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Identify limitations and uses of EdgerRouter family (including EdgePoint)

EP‑R6 is a nice 5 port outdoor router with poe that should be compatible with EdgeRouter X.

https://www.ui.com/edgemax/edgepoint/

## To Do
- [x] Will babeld run on stock os?
- [x] Make it presistant
- [x] Survive upgrades?
- [x] Build DEB package
- [x] Config
- [x] Hardware Offload for TCP/UDP routes at full gige
- [x] Identify VPN/TUNNEL options

EdgeRouter X SFP doubles as a 5 port POE switch.

**Comment by darkdrgn2k** [comment]
Configure Internet Port
```

    delete interfaces ethernet eth0 address 192.168.1.1/24
    set interfaces ethernet eth0 address 192.168.40.55/24    
    set interfaces ethernet eth0 address fd74:6f6d:7368:400a::1
    set interfaces ethernet eth0 ip
    set interfaces ethernet eth0 description "Gateway Internet"
    set protocols static route 0.0.0.0/0 next-hop 192.168.40.1 description "Gateway Interent"

```

Configure other 4 ports for LAP ports
```
    delete interfaces ethernet eth1 address dhcp
    set interfaces ethernet eth1 address 100.64.10.1/24
    set interfaces ethernet eth1 address fd74:6f6d:7368:400a::1/64
    set interfaces ethernet eth2 address 100.64.11.1/24
    set interfaces ethernet eth2 address fd74:6f6d:7368:400b::1/64
    set interfaces ethernet eth3 address 100.64.12.1/24
    set interfaces ethernet eth3 address fd74:6f6d:7368:400c::1/64
    set interfaces ethernet eth4 address 100.64.13.1/24
    set interfaces ethernet eth4 address fd74:6f6d:7368:400d::1/64
```

DHCP

```
set service dhcp-server disabled false
delete service dhcp-server shared-network-name
set service dhcp-server shared-network-name 100.64.10.0 authoritative enable
set service dhcp-server shared-network-name 100.64.10.0 subnet 100.64.10.0/24 default-router 100.64.10.1
set service dhcp-server shared-network-name 100.64.10.0 subnet 100.64.10.0/24 dns-server 1.1.1.1
set service dhcp-server shared-network-name 100.64.10.0 subnet 100.64.10.0/24 domain-name to.mesh
set service dhcp-server shared-network-name 100.64.10.0 subnet 100.64.10.0/24 lease 600
set service dhcp-server shared-network-name 100.64.10.0 subnet 100.64.10.0/24 start 100.64.10.127 stop 100.64.10.254

set service dhcp-server shared-network-name 100.64.11.0 authoritative enable
set service dhcp-server shared-network-name 100.64.11.0 subnet 100.64.11.0/24 default-router 100.64.11.1
set service dhcp-server shared-network-name 100.64.11.0 subnet 100.64.11.0/24 dns-server 1.1.1.1
set service dhcp-server shared-network-name 100.64.11.0 subnet 100.64.11.0/24 domain-name to.mesh
set service dhcp-server shared-network-name 100.64.11.0 subnet 100.64.11.0/24 lease 600
set service dhcp-server shared-network-name 100.64.11.0 subnet 100.64.11.0/24 start 100.64.11.127 stop 100.64.11.254

set service dhcp-server shared-network-name 100.64.12.0 authoritative enable
set service dhcp-server shared-network-name 100.64.12.0 subnet 100.64.12.0/24 default-router 100.64.12.1
set service dhcp-server shared-network-name 100.64.12.0 subnet 100.64.12.0/24 dns-server 1.1.1.1
set service dhcp-server shared-network-name 100.64.12.0 subnet 100.64.12.0/24 domain-name to.mesh
set service dhcp-server shared-network-name 100.64.12.0 subnet 100.64.12.0/24 lease 600
set service dhcp-server shared-network-name 100.64.12.0 subnet 100.64.12.0/24 start 100.64.12.127 stop 100.64.12.254

set service dhcp-server shared-network-name 100.64.13.0 authoritative enable
set service dhcp-server shared-network-name 100.64.13.0 subnet 100.64.13.0/24 default-router 100.64.13.1
set service dhcp-server shared-network-name 100.64.13.0 subnet 100.64.13.0/24 dns-server 1.1.1.1
set service dhcp-server shared-network-name 100.64.13.0 subnet 100.64.13.0/24 domain-name to.mesh
set service dhcp-server shared-network-name 100.64.13.0 subnet 100.64.13.0/24 lease 600
set service dhcp-server shared-network-name 100.64.13.0 subnet 100.64.13.0/24 start 100.64.13.127 stop 100.64.13.254
```


L2TP 
```


    set interfaces l2tpv3 l2tpeth0 description "To Exit Node NJ"
    set interfaces l2tpv3 l2tpeth0 destination-port 5000
    set interfaces l2tpv3 l2tpeth0 local-ip 192.168.40.55
    set interfaces l2tpv3 l2tpeth0 mtu 1412
    set interfaces l2tpv3 l2tpeth0 peer-session-id 1000
    set interfaces l2tpv3 l2tpeth0 peer-tunnel-id 3000
    set interfaces l2tpv3 l2tpeth0 remote-ip 199.195.250.209
    set interfaces l2tpv3 l2tpeth0 session-id 2000
    set interfaces l2tpv3 l2tpeth0 source-port 6000
    set interfaces l2tpv3 l2tpeth0 tunnel-id 4000

    set interfaces l2tpv3 l2tpeth0 address 100.127.2.2/30
    set interfaces l2tpv3 l2tpeth0 address fd74:6f6d:7368:7f02::2/126

```

(other side)
```

EXITIP=199.195.250.209
CLIENTIP=76.69.75.163
#EXIT
ip l2tp delete tunnel tunnel_id 3000
ip l2tp add tunnel tunnel_id 3000 peer_tunnel_id 4000 encap udp local $EXITIP remote $CLIENTIP udp_sport 5000 udp_dport 6000
ip l2tp add session tunnel_id 3000 session_id 1000 peer_session_id 2000
ip link set l2tpeth0 up mtu 1412
ip addr add dev l2tpeth0 100.127.2.1/30
ip addr add dev l2tpeth0 fd74:6f6d:7368:7f02::1/126
```



BABELD
install using https://github.com/darkdrgn2k/RouterX-Babeld-Package

```


    set protocols babeld denydefault true
    set protocols babeld denydefaultlocal true
    set protocols babeld interface l2tpeth0
    set protocols babeld interface eth1
    set protocols babeld interface eth2
    set protocols babeld interface eth3
    set protocols babeld interface eth4
    
    set protocols babeld filter eth1 action allow
    set protocols babeld filter eth1 if eth1
    set protocols babeld filter eth1 type redistribute

    set protocols babeld filter eth2 action allow
    set protocols babeld filter eth2 if eth2
    set protocols babeld filter eth2 type redistribute

    set protocols babeld filter eth3 action allow
    set protocols babeld filter eth3 if eth3
    set protocols babeld filter eth3 type redistribute


    set protocols babeld filter eth4 action allow
    set protocols babeld filter eth4 if eth4
    set protocols babeld filter eth4 type redistribute

    set protocols babeld filter l2tpeth0 action allow
    set protocols babeld filter l2tpeth0 if l2tpeth0
    set protocols babeld filter l2tpeth0 type redistribute



```

**Comment by darkdrgn2k** [comment]
Enable DNS (need to find a better way of doing this then running full dns)

```
    delete service dns
    set service dns forwarding name-server 1.1.1.1
    set service dns forwarding listen-on eth1
    set service dns forwarding listen-on eth2
    set service dns forwarding listen-on eth3
    set service dns forwarding listen-on eth4
```

**Comment by darkdrgn2k** [comment]
Certifictes
```
cat <<"EOF">/config/auth/SN1R1.crt
-----BEGIN CERTIFICATE-----
MIIE+zCCA+OgAwIBAgIBAjANBgkqhkiG9w0BAQsFADCBlzELMAkGA1UEBhMCQ0Ex
CzAJBgNVBAgTAk9OMRAwDgYDVQQHEwdUb3JvbnRvMRUwEwYDVQQKEwxUb3JvbnRv
IE1lc2gxDzANBgNVBAsTBnRvbWVzaDEPMA0GA1UEAxMGdG9tZXNoMQ8wDQYDVQQp
EwZ0b21lc2gxHzAdBgkqhkiG9w0BCQEWEGhlbGxvQHRvbWVzaC5uZXQwHhcNMjAw
NzIwMjAxMjIxWhcNMzAwNzE4MjAxMjIxWjCBhjELMAkGA1UEBhMCQ0ExCzAJBgNV
BAgTAk9OMRAwDgYDVQQHEwdUb3JvbnRvMQ8wDQYDVQQKEwZ0b21lc2gxDzANBgNV
BAsTBnRvbWVzaDENMAsGA1UEAxMEUzFSMTEQMA4GA1UEKRMHRWFzeVJTQTEVMBMG
CSqGSIb3DQEJARYGdG9tZXNoMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEA0AF8YupaNfcdUZTmBuBhn731nxvsHEU9oHb4gt+HYTlFkaG7AyeRmYufC3zW
yIZCCq2rEbUEdUjsQSGtGKfBsnXit5MCG85EJ8pHzzQVON9X8EUf7oPPVHFhj5QJ
fkH32lmJNbsMuLf7gudAbeQ5nnJkAhLPhX9m99tLPUPDxf13vu+SQOhaC8mbCS20
OQw1AFxh1B3vIq4xKhKtZiOTY2UmwWWggBKUU2hzOH2BDhFxR47fGbUN2muueQ+l
9w21QSCSFKQ67xXqXouEJZ+Z8h+cjVI6VOLyrAl1nk9hPGRFo9iq/rwQUqLqROrB
U3rjKr3HE+DTRSPJxyBt6ZvPlwIDAQABo4IBXzCCAVswCQYDVR0TBAIwADAtBglg
hkgBhvhCAQ0EIBYeRWFzeS1SU0EgR2VuZXJhdGVkIENlcnRpZmljYXRlMB0GA1Ud
DgQWBBQ2piuebf5BY4fZOQGRWSwWcXNu8TCBzAYDVR0jBIHEMIHBgBTO4DJkR8GI
+8vugdBYB+R8w4Lw7aGBnaSBmjCBlzELMAkGA1UEBhMCQ0ExCzAJBgNVBAgTAk9O
MRAwDgYDVQQHEwdUb3JvbnRvMRUwEwYDVQQKEwxUb3JvbnRvIE1lc2gxDzANBgNV
BAsTBnRvbWVzaDEPMA0GA1UEAxMGdG9tZXNoMQ8wDQYDVQQpEwZ0b21lc2gxHzAd
BgkqhkiG9w0BCQEWEGhlbGxvQHRvbWVzaC5uZXSCCQCIsD2EuZq/QDATBgNVHSUE
DDAKBggrBgEFBQcDAjALBgNVHQ8EBAMCB4AwDwYDVR0RBAgwBoIEUzFSMTANBgkq
hkiG9w0BAQsFAAOCAQEAmAQTzyjtzreo0Qi0gDMbZFOl/K4SqYErrqevdFf4smzf
zY61YRb0qPqQ+Wku6bE5d7fEhf3kZqjdJWBpi+uf0soWe9jbiDUK+fEC+52gDo+A
RFG0TVHCMlM1shBzO8VROSIAY3jeNjL9QciZvKwpHCqqeOXtFTWvQrvIzqRYcI99
FDS3v76zRoLPUtiI3JLr4rNBQWMjEKnD+DQ9jTXER3hH02QtzEvAuIJPqOHFUzvF
k6LlGy4z6C/ctHHuQ9Ez4q5UwkQU49kMU89kjDAS6v+Pnd0k+LvFTNYlIGNj7+UJ
DOi7mimnSi5jyu6xLAMJ1eBn4bbupxj55J9+2LXjCw==
-----END CERTIFICATE-----
EOF
cat <<"EOF">/config/auth/SN1R1.key
-----BEGIN PRIVATE KEY-----
<<SANITIZED>>
-----END PRIVATE KEY-----
EOF
cat <<"EOF"> /config/auth/ca.crt
-----BEGIN CERTIFICATE-----
MIIEszCCA5ugAwIBAgIJAIiwPYS5mr9AMA0GCSqGSIb3DQEBCwUAMIGXMQswCQYD
VQQGEwJDQTELMAkGA1UECBMCT04xEDAOBgNVBAcTB1Rvcm9udG8xFTATBgNVBAoT
DFRvcm9udG8gTWVzaDEPMA0GA1UECxMGdG9tZXNoMQ8wDQYDVQQDEwZ0b21lc2gx
DzANBgNVBCkTBnRvbWVzaDEfMB0GCSqGSIb3DQEJARYQaGVsbG9AdG9tZXNoLm5l
dDAeFw0yMDA3MjAyMDEwNTNaFw0zMDA3MTgyMDEwNTNaMIGXMQswCQYDVQQGEwJD
QTELMAkGA1UECBMCT04xEDAOBgNVBAcTB1Rvcm9udG8xFTATBgNVBAoTDFRvcm9u
dG8gTWVzaDEPMA0GA1UECxMGdG9tZXNoMQ8wDQYDVQQDEwZ0b21lc2gxDzANBgNV
BCkTBnRvbWVzaDEfMB0GCSqGSIb3DQEJARYQaGVsbG9AdG9tZXNoLm5ldDCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMkWwPiHTd9T1a82HXAJao771ZRJ
1438yx6Ovm8mt+Z6MZ0r87BZ/pQ1TjcAgPNoV2TfnXkj8I1x2hoOub/EUu+WAYtf
54Ozjse1nUEiXB8WHNTh1VsYqcDlna16Js9/jcK+WkQvolf9bHZgwzJxqV62Yt+P
0pFPoIFsU4otdNCBKHmPF3UvEhq7Xa+BY3mtfFf6AIz/cjuS4sODz/jiNV9FfEbg
0aW6/NOuM/TbUy7Cu3ubuf5ESMnI20jEBhln+ksCkzqLANegdMRp8d7WZxYkvdgb
CYX9hRL83hQe2jhwijYw0DXvR5CqUwJXg8ERuRoxtpoNx00nuuk2dVY3gwUCAwEA
AaOB/zCB/DAdBgNVHQ4EFgQUzuAyZEfBiPvL7oHQWAfkfMOC8O0wgcwGA1UdIwSB
xDCBwYAUzuAyZEfBiPvL7oHQWAfkfMOC8O2hgZ2kgZowgZcxCzAJBgNVBAYTAkNB
MQswCQYDVQQIEwJPTjEQMA4GA1UEBxMHVG9yb250bzEVMBMGA1UEChMMVG9yb250
byBNZXNoMQ8wDQYDVQQLEwZ0b21lc2gxDzANBgNVBAMTBnRvbWVzaDEPMA0GA1UE
KRMGdG9tZXNoMR8wHQYJKoZIhvcNAQkBFhBoZWxsb0B0b21lc2gubmV0ggkAiLA9
hLmav0AwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAjdLedME06tE3
WZgZlA20TdlMThdV67hkKBZbGUhlIqJuaykSi2Fp8zVg5CxgGNOp5GJRQ2z1rMtr
dPSIV6lYxfFgGTqfBRyw4dMyfDxA2XO3mMlTJzVNYcE1zXJp75ZpLxUEhcPNllYa
l481UxG2SQdQh9UPrtKJxf3KSTvRJufzxrh6i3iPmZRzLhPt7Vc+aCYjUFq+EJ/z
q1ACKn0pA8H3YbbdhA/RPQh3CRKiuE4kdq3BP4YYjW8xysrEU3TKfXHz4BY1OTPl
JxRDuteL3nTPh22VfcY/j6OeVtGKg+BGJv4xRDEb0a0xx58Ki+9R6TPotNuHYj1L
clmLw8d8Ew==
-----END CERTIFICATE-----
EOF
```
Configure OPENVPN

```
    set interfaces openvpn vtun99 mode client
    set interfaces openvpn vtun99 protocol udp
    set interfaces openvpn vtun99 remote-host 198.98.49.249
    set interfaces openvpn vtun99 remote-port 4141
    set interfaces openvpn vtun99 tls ca-cert-file /config/auth/ca.crt
    set interfaces openvpn vtun99 tls cert-file /config/auth/SN1R1.crt
    set interfaces openvpn vtun99 tls key-file /config/auth/SN1R1.key
```

**Comment by darkdrgn2k** [comment]
OpenVPN Server config

```
topology subnet
port 4141
proto udp
dev tun99
ca ca.crt
cert tomesh.crt
key tomesh.key
dh dh2048.pem
script-security 2
server 100.127.254.0 255.255.255.0
client-to-client
keepalive 10 120
persist-key
persist-tun
log    "/var/log/openvpn.log"
verb 3
client-config-dir /etc/openvpn/ccd/
ifconfig-pool-persist /etc/openvpn/ipp

```

**Comment by darkdrgn2k** [comment]
# Lab Setup

- Factory Reset
- Configured eth4 to 10.10.4.1/24
- Configured eth3 to 10.10.3.1/24
- Added DHCP-Server for both subnet
  - 10.10.x.100-254
  - Default Route 10.10.x.1

![image](https://user-images.githubusercontent.com/29005789/88973359-f79d0400-d284-11ea-8828-5c645f83ff50.png)

# Straight Routing
# HWNAT  Disabled
![image](https://user-images.githubusercontent.com/29005789/88973524-359a2800-d285-11ea-8ac6-dff274bcd030.png)
- 400-500Mpbs ksoftirq at 99% CPU

## HWNAT Enabled 

`system offload hwnat enable`

![image](https://user-images.githubusercontent.com/29005789/88973646-68dcb700-d285-11ea-985a-90d803309b7f.png)
- 850-900pbs ksoftirq not listed 

#  GRE Tunnel
Raspberry on Eth 3
```
sudo ip tunnel add gre1 mode gre local 10.10.3.100 remote 10.10.4.100 ttl 255
sudo ip addr add 10.0.0.1/30 dev gre1
sudo ip link set gre1 up
```
Raspberry on Eth 4
```
sudo ip tunnel add gre1 mode gre local 10.10.4.100 remote 10.10.3.100 ttl 255
sudo ip addr add 10.0.0.2/30 dev gre1
sudo ip link set gre1 up
```
# HWNAT  Disabled
![image](https://user-images.githubusercontent.com/29005789/88973811-b0fbd980-d285-11ea-8a68-7840aeb3024a.png)
- 400-500Mpbs ksoftirq at 99% CPU

## HWNAT Enabled 

`system offload hwnat enable`

![image](https://user-images.githubusercontent.com/29005789/88973907-cc66e480-d285-11ea-9445-79465e303013.png)
- 400-500Mpbs ksoftirq at 99% CPU

**Comment by darkdrgn2k** [comment]
Install irqbalancer test

```
curl http://http.us.debian.org/debian/pool/main/libc/libcap-ng/libcap-ng0_0.7.7-3+b1_mipsel.deb -o libcap-ng0_0.7.7-3+b1_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/n/numactl/libnuma1_2.0.11-2.1_mipsel.deb -o libnuma1_2.0.11-2.1_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/libf/libffi/libffi6_3.2.1-6_mipsel.deb -o libffi6_3.2.1-6_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/g/glibc/libc6-mipsn32_2.24-11+deb9u4_mipsel.deb -o libc6-mipsn32_2.24-11+deb9u4_m
curl http://http.us.debian.org/debian/pool/main/g/glibc/libc6_2.24-11+deb9u4_mipsel.deb -o libc6_2.24-11+deb9u4_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/g/glib2.0/libglib2.0-0_2.50.3-2+deb9u2_mipsel.deb -o libglib2.0-0_2.50.3-2+deb9u2_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/libg/libgpg-error/libgpg-error0_1.26-2_mipsel.deb -o libgpg-error0_1.26-2_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/libg/libgcrypt20/libgcrypt20_1.7.6-2+deb9u3_mipsel.deb -o libgcrypt20_1.7.6-2+deb9u3_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/l/lz4/liblz4-1_0.0~r131-2+b1_mipsel.deb -o liblz4-1_0.0~r131-2+b1_mipsel.deb 
curl http://http.us.debian.org/debian/pool/main/s/systemd/libsystemd0_232-25+deb9u12_mipsel.deb -o libsystemd0_232-25+deb9u12_mipsel.deb
curl http://http.us.debian.org/debian/pool/main/i/irqbalance/irqbalance_1.1.0-2.3_mipsel.deb -o irqbalance_1.1.0-2.3_mipsel.deb

```
