### ISSUE TITLE
Formal Proposal

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#27]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Send out formal proposal to all contacts.

Create proposal for longer vision of toronto mesh.

## To Do

- [ ] Discuss future of this document
- [ ] Finish draft
- [ ] Run it through Hank 
- [ ] Send it to individuals that could get behind it.
