### ISSUE TITLE
200 WOOLNER Deployment

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#29]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** 7/24/2020
🎯 **Success criteria:** Nodes are up and running and ready to receive connections

Location: https://goo.gl/maps/qvdh4f49L7tQpPKt6 (200 Woolner Ave)

**NOTE** We will be limiting the amount of people on the roof to about 2 at a time.  
If your interested in participating (on the roof or on the ground) please make sure you get in touch with us (hello@tomesh.net)

COVID NOTICE: If you will be attend please bring a mask or face covering.

We will be deploying along side the CITY FREE WIFI PROJECT on Thursday, July 23 and Friday July 24th.

The project window will be between 9-5 on each day.
Toronto mesh will attend 
- Thursday 12:01 pm - 5:00 pm (to allow for infra deployment by other teams first)
- Friday 9:00 am - 5:00 pm

Goal is to have everything operational by end of Friday.
![image](https://user-images.githubusercontent.com/29005789/88209645-02bab900-cc21-11ea-90ff-33c71803a834.png)

Weather outlook shows possible thunderstorms on Thursday. For safety reasons we will NOT be on the roof if there is any evidence of severe weather.

## What to bring with you

- [ ] Mask
- [ ] Weather gear
   - Sunblock
   - Sun Glasses 
   - Hat 
- [ ] Laptop (charged)
- [ ] Phone (charged) 
- [ ] Food/Water/Whatever else you need for the day

## To Do
- [ ] Shopping list
  - [x] LAP x4
  - [x] Edgerouter X-SFP
  - [x] Cable Clamps, stainless steal x8
  - [x] UV resistant Zip Ties
  - [x] RJ45 connectors
  - [ ] 1ft extension cable x2
  - Tools
    - [x] RJ45 Crimpers
    - [x] Line Testers
    - [x] Screwdrivers
    - [ ] socket set
    - [x] Channel Lock
    - [ ] Compass
- [x] Pre-configured hardware 
  - [x] 4xLAP
  - [x] 1x EdgeRouter

**Comment by darkdrgn2k** [comment]
Deployment successful of two antennas

![image](https://user-images.githubusercontent.com/29005789/88391601-8347f980-cd88-11ea-96e4-ad1280433382.png)
