### ISSUE TITLE
Establish online store

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#3]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Open functional online store.

...

## To Do

- [ ] Look into free geek capability to support
    - [ ] Investigate allocation of funds from IPFS grant
    - [ ] If needed, investigate if Open Collective can help (need to involve Hypha)
- [ ] Get stock
- [ ] Start selling

**Comment by benhylau** [comment]
I can sort this with Free Geek after the fiscal hosting relationship is solidified. Don't want to add more items into the mix for now and perhaps not super urgent until we have secured funds for initial stock.

I am adding a couple items to the top issue:

1. There is some funds from [an earlier IPFS grant](https://github.com/tomeshnet/p2p-internet-workshop/issues/55) that has overlapping scope: 
     > - Making hardware easily accessible (e.g. support cheaper/readily available hardware, investigate selling as package on Tindie, etc.)

2. Investigate the use of [Hypha's Open Collective](https://opencollective.com/hyphacoopinc/) as a sales channel
    - My preference is to have Free Geek handle all aspects of the hardware sales, but OC may be available should it be needed

**Comment by benhylau** [comment]
Blocked for same reason as #19, we need to first figure out what is the setup to connect and sell that thru the online store.
