### ISSUE TITLE
Consistency of names across different spaces

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#30]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** asap  
🎯 **Success criteria:** Agree on a set of terms we will use consistently across different spaces.  

I would like us to agree on a set of terms and use them consistently across different spaces. Any deviation should be treated as an error and fixed. Otherwise, it is massively confusing for new people coming onboard to understand our communications, when the same thing is referred to in many ways. (e.g. Is Toronto Mesh same as TOMesh? What is the relation between Toronto Mesh, Toronto Community Network, Free WiFi Project?)

I propose the following, and stick to it religiously. If there is any disagreement or new term we need to define, let's list them here and we agree on their use.

### `Toronto Mesh`
_Written upper case T and upper case M._

This is how this group is formally referred to in different spaces (e.g. [on our website timeline](https://tomesh.net/timeline/), [CoC](https://tomesh.net/code-of-conduct/), all external communications and articles written by others). It is not `TOMesh`, `TO Mesh`, or `Toronto Meshnet`.

### `Toronto Community Network` 
_Written upper case T, upper case C, and upper case N._

The name of this particular initiative. It is the name we agreed on and put into all proposal material shared with collaborators.

### `City of Toronto's Free WiFi Project` / `Toronto Free WiFi Project`
The working title of the project that the City is working on with its partners to offer free WiFi to neighbourhoods in need, as emergency response to the covid-19 pandemic.

### `tomeshnet`
_Written all lower case._

This is our account handle on different services and social media (e.g. [Twitter](https://twitter.com/tomeshnet), [GitHub](https://github.com/tomeshnet)).

### `tomesh`
_Written all lower case._

Sometimes used as a short form to refer to Toronto Mesh in informal situations. This short form should never be used on published documents or official communication.

### `tomesh.net`
_Written all lower case._

Our website. It is without the `www.` in front.

### `supernode`

A `supernode` is an actively maintained relaying node that supports high bandwidth point-to-multipoint (PTMP) connectivity. Currently all supernodes are managed by the Network Planning, Design and Operations working group at Toronto Mesh, but other groups may also operate their own supernodes on the Toronto Community Network.

## To Do

- [x] Agree to adopt (please 👍 on this or comment in issue)
- [x] Update this repository name to `toronto-community-network` (this name is confusing esp. since we have `deployment` repo)
- [x] Change references that are incorrect

**Comment by Shrinks99** [comment]
In what instances is "tomesh" used?  Code comments?  Should we not just be using the standard "Toronto Mesh instead?

**Comment by benhylau** [comment]
Only when in chat and comments like here, tomesh (6 char) without having to type the whole thing out

**Comment by Shrinks99** [comment]
I almost don't want to make it an "official" short form but it's also our website domain... 🤔

**Comment by benhylau** [comment]
I feel ppl will type a short in chat anyways, and it's better to do that than TOMesh/TOMESH/Tomesh/TOMesh/TO  Mesh...

**Comment by darkdrgn2k** [comment]
> Update this repository name to toronto-community-network (this name is confusing esp. since we have deployment repo)

Just wanted to point out that the reason we mane "mesh-deployment" was because we needed to make a private repo.
The plan was to REPLACE the deployment repo .

Is there any advantage of using "toronto-community-network" over simply "deployment"

Currently the deployment repo  really does not have any valuable content.

**Comment by benhylau** [comment]
>Is there any advantage of using "toronto-community-network" over simply "deployment"

The project proposal involves many components that are not really related to "deployment". If the intention is to separate out things into many repos, that's a larger convo, and perhaps we should then move the deployment tickets (those tagged network) to the deployment repo. (There is a feature to do this easily.) This looks like a repo for planning the overall project, that's why it hosts tags like `communications` and `governance`, which I believe gets confusing when in a "deployment" repo. The content in the repo also is the overall plan that extends beyond network deployment.

>As opposed to what initiative? How far does "this initiative" stretch?

The initiative described here https://github.com/tomeshnet/toronto-community-network/tree/master/published-documents

It excludes ipfs-live-streaming, p2p-internet-workshop, prototype, etc.

**Comment by Shrinks99** [comment]
The rationale for renaming this repo makes sense to me but the deployment repo should probably also be removed.  It has one document in it (which can be moved to the documents repo) and all the issues are pretty much made obsolete by this initiative.  I am for moving that document and outright deleting or archiving the deployment repo.

**Comment by benhylau** [comment]
Yea pls do and archive it

**Comment by benhylau** [comment]
Some terms we can add to a glossary or @tomeshnet/communications-and-community-engagement can use for website copy:

A **supernode** is an actively maintained relaying node that supports high bandwidth point-to-multipoint (PTMP) connectivity. Currently all supernodes are managed by the Network Planning, Design and Operations working group at Toronto Mesh, but other groups may also operate their own supernodes on the Toronto Community Network.

The **supernode name** is `snXyY` and  where `X` is assigned by the _Network Planning, Design and Operations_ working group, and `yY` is chosen by the node operator to identify network components within the node. For example `a1` for antenna 1 and `r1` for router 1.

The **supernode domain** is in the format `nodename.operator.tcn.tomesh.net`. For example `sn1a1.core.tcn.tomesh.net` for a device operated by the core team at Toronto Community Network.

**Comment by darkdrgn2k** [comment]
Added definition of SUPERNODE to first post on this issue

Super Node naming standards added to issue  #21 

*NOTE* 
NOSTNAME is `snXyY`
DOMAIN is `operator.tcn.tomesh.net`
FQDN (fully qualified domain name) would be a mix of the two - `snXyY.operator.tcn.tomesh.net`

**Comment by benhylau** [comment]
This needs to be documented in our #54 eventually, but I'd say this task is done now since success criteria is met and I am unaware of incorrect references in any official place.

**Comment by makeworld-the-better-one** [comment]
Could an abbreviation of `Toronto Community Network` as `TCN`/`tcn` be added? It is already in use in domain names.
