### ISSUE TITLE
Supernode 1 Field Testing

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#34]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** 7/24/2020
🎯 **Success criteria:** Collect data from different points about strenght and speed of node.

## To Do

- [x] Collect data on link quality with AirMaxAC from the ground where there is LOS
- [x] Convert to documentation somewhere
## Tools required

- [x] AC Battery  or Car cigarette liter Inverter (one of each)
- [x] Loco or LiteBeam (two of each)

**Comment by darkdrgn2k** [comment]
- Drive to location where there is a LOS to the node
- Position LocoAC or LiteBeamAC at Node
- Record location (Long, Lat, Alt), and Device Used, take a picture pointing at the Super Node
- Use the onboard positioning tool to get the best signal possible
- Perform Speed 3 tests and record the information

**Comment by darkdrgn2k** [comment]
5 Points tested in the neighborhood against sn1a1

| Point   | Distance   | Adjusted  | Ping   |  Speed RX/TX  |
|----------|---------------|--------------|----------|-------------|
| a         |   200m      |  210m     |             |  86x194  |
| b         |   200m      |   210m    |             |                |
| c         |   210m      |   258m    |             |                |
| d         |   250m      |   275m    |             |                |
| e         |   270m      |   358m    |             |                |

a	200m	210m
b	200m	210m
c	250m	258m
d	270m	278m
e	380m	358m

Point A and B
![image](https://user-images.githubusercontent.com/29005789/88433759-af856980-cdcc-11ea-88d0-8576758af43e.png)

Point E
![image](https://user-images.githubusercontent.com/29005789/88433774-b8763b00-cdcc-11ea-8c09-588b0cefba06.png)

Point F
![image](https://user-images.githubusercontent.com/29005789/88434899-2885c080-cdcf-11ea-902c-fd5567a18324.png)
![image](https://user-images.githubusercontent.com/29005789/88434911-2f143800-cdcf-11ea-898b-b3a48fca55a7.png)

**Comment by darkdrgn2k** [comment]
Re-tested POINT F using Antenna `sn1a2`.

- at start it would not connect again

```
Jun 23 16:45:10 wireless: ath0     Set Mode:Managed
Jun 23 16:45:35 wireless: ath0     Scan request completed
Jun 23 16:45:35 wireless: ath0     Set Mode:Managed
Jun 23 16:45:35 wireless: ath0     Set Frequency:5.31 GHz (Channel 62)
Jun 23 16:46:01 wireless: ath0     Scan request completed
Jun 23 16:46:01 wireless: ath0     Set Mode:Managed
Jun 23 16:46:01 wireless: ath0     Set Frequency:5.31 GHz (Channel 62)
```
- logged in to sn1a2 (over management vpn, exit node was down due to power issues)
- was met with a crash report
![image](https://user-images.githubusercontent.com/29005789/88493497-75a89480-cf7f-11ea-9cec-29d962983a85.png)
- POE  cycled on sn1r1  to power cycle the antenna
- After reboot connection was made

![image](https://user-images.githubusercontent.com/29005789/88493551-b56f7c00-cf7f-11ea-8c79-53f8c4e3b8a2.png)

- Performed speed tests and alignment measures

Signal Strength: 
Local -85 (-86/90)  Delta 4 
Remote  -83 (-89/-94) delta 5

Speed Tests
- 4.04/12.97
- 28 (Receive Only)
- 26 (Send only)

- looking at the spectral analysis found channel being used was very loud (DFS scan prevent seeing it before)

![image](https://user-images.githubusercontent.com/29005789/88493664-4e05fc00-cf80-11ea-8b4a-2b6cbb102a57.png)

- Moved antenna to another frequency and performed speed test

10.15Mbps TX /54.13Mbps RX
11.91Mbps TX/62.98 RX
Signal Strength ~ -71
![image](https://user-images.githubusercontent.com/29005789/88493712-9b826900-cf80-11ea-81f6-748576c8a355.png)


- Noticed that tx power was very low for the LiteBeam (only 5dBi)
- Increased power of LAP-120 from 11dBi to 12dBi
- Confirmed LiteBeam power was set to 24dBi but reports 5dBi
  - unChecked "auto ajust power level"
  - unchecked 'ERI calculation"
  - got 24dBi

- Ran tests at 24dBi

40.79MBps/64.58Mbps 

![image](https://user-images.githubusercontent.com/29005789/88493759-e7cda900-cf80-11ea-8500-7d743803db44.png)



Other Observations/details
-  tried lowering the bandwidth to 10Mhz but did not work, i think you need to do it on both antennas. Left it for now.
- sn1a1 showed on scan only when antenna was pointed fairly well, however sn1a2 showed up as long as the antennas was in the general direction. Should confirm sn1a1 is the south facing antenna
![image](https://user-images.githubusercontent.com/29005789/88493837-45fa8c00-cf81-11ea-9e87-6bd31bf064f3.png)
- picked up toronto.ca/wifi ssids in scans
![image](https://user-images.githubusercontent.com/29005789/88493854-527ee480-cf81-11ea-9039-d1d8d88fcedf.png)

-

**Comment by makeworld-the-better-one** [comment]
> Collect data on link quality with AirMaxAC from the ground where there is LOS

Is this still left to do?

**Comment by benhylau** [comment]
_This task is in `Doing` state so at least one person should be assigned. Can @makeworld-the-better-one or @darkdrgn2k assign themselves? This ensures someone takes personal responsibility of getting it done :) thanks!_

**Comment by makeworld-the-better-one** [comment]
I don't think I have the capability or hardware to complete this task, and I'm not sure exactly what's left to do. If @darkdrgn2k can assign himself that'd be great, and let me know how I can assist if needed.

**Comment by darkdrgn2k** [comment]
I think this is more or less completed.

There is one more test id like to do and that's the loco at 2.5km
