### ISSUE TITLE
Contributor onboarding process

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#35]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** asap  
🎯 **Success criteria:** Establish onboarding workflow for new contributors.  

If someone says they want to help, we need a standardized way to quickly engage and onboard them into our spaces and workflow. I imagine getting their email and send an onboarding templated email that includes steps to get onto our working groups on GitHub, chat, etc. followed by a peer session to explain how to use the tools and our collaboration practices.

## To Do

- [x] Create a one-pager to onboard email template (put in this repo), this should include:
  - WGs in GitHub Teams
  - Project board and tasks
  - Element chat
  - Mailing list (main mailman list and forwarder)
  - Meeting time poll (for each WG)
  - Responsibilities and CoC
- [x] Send this to existing contributors
- [x] Do a walkthru together on workflow
- [x] Designate someone in @tomeshnet/project-operations to respond to new onboarding emails moving forward

**Comment by benhylau** [comment]
@ASoTNetworks can you set up the following addresses:

- operations@tomesh.net
- communications@tomesh.net
- network@tomesh.net
- governance@tomesh.net

and have all of them just forward to you. Then once the bootstrap email goes out to the existing `deployment@` email, ppl will reply with their email and GitHub handle, and you get slot them into the correct forwarder and GitHub team?

**Comment by ASoTNetworks** [comment]
Email forwarders have been made.

**Comment by benhylau** [comment]
Made #40 with @Shrinks99 and emailed trial email to @Shrinks99 and @ASoTNetworks. Please respond as instructed by the email as if you have no idea of this process.

**Comment by benhylau** [comment]
@Shrinks99 I sent this to `deployment@` and @ceresstation.

Can you send the same email to Io, and temporarily handle this task after the `Get Involved` section of the website is updated?

You basically [copy and paste from this view](https://github.com/tomeshnet/toronto-community-network/blob/master/communications/email-templates/new-contributor.md) (all the links should carry over to your MacOS mail client), fill in the Subject/Cc/Reply-To as listed and send to the new contributor.

**Comment by benhylau** [comment]
>Do a walkthru together on workflow

I also propose that we do put up an event to:

- go through the task workflow
- set task priorities
- decide working group meeting hours
- show and tell first node installation

How about first week of August?

**Comment by makeworld-the-better-one** [comment]
Potentially the contributor onboarding process could be documented in our book, see #54.

**Comment by benhylau** [comment]
>- Designate someone in @tomeshnet/project-operations to respond to new onboarding emails moving forward

@ASoTNetworks do you want to take this role as part of @tomeshnet/project-operations? It would involve you managing membership of the ppl in the mailing lists and github teams, plus replying to their email cc'ing their WGs to introduce them, then the WG can follow up with the onboard like how @darkdrgn2k is doing now for @tomeshnet/network-planning-design-and-operations with @digitaldina.

@digitaldina we are also trialing this onboard process for future new members, so pls raise any friction point you see and we can fix it :)

**Comment by ASoTNetworks** [comment]
Sure I can do that.
