### ISSUE TITLE
ISOC Funding

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#4]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** 
  - Submit ISOC Proposal -  6/22/2020
🎯 **Success criteria:** Receive access to ISOC Funding.

...

## To Do

- [x] Draft ISOC Proposal
- [x] Meetings to review proposal
- [x] Free Geek #2 
- [x] Submit ISOC Proposal
- [x] Get ISOC approval
- [x] Receive access to money @benhylau 
  - [x] Sign Memorandum of Understanding (MoU) between Toronto Mesh and Free Geek Toronto
  - [x] Confirm Free Geek has received money
  - [x] Confirm Free Geek expense and reimbursement process
  - [x] Agree on approval process from Toronto Mesh
  - [x] Assign roles in the process
  - [x] Document process and roles in docs.tomesh.net
- [x] Hold meeting with @ryan-fgt with Administrators (see https://github.com/tomeshnet/toronto-community-network/issues/2#issuecomment-698627958)

**Comment by benhylau** [comment]
@TimTor @Pedro-on-a-bike @ryan-fgt @ultush pls review https://github.com/tomeshnet/toronto-community-network-docs/blob/finances/src/operations/finances.md

**Comment by benhylau** [comment]
https://github.com/tomeshnet/toronto-community-network-docs/pull/20 this has been merged covering all of the ISOC grant documenting.

**Comment by benhylau** [comment]
@Shrinks99 @YurkoWasHere @TimTor pls sign MoU and upload to the `Signed MoUs` folder asap. If anyone has questions lmk https://cloud.tomesh.net/apps/files/?dir=/tomeshnet-trusted/Internet%20Society/2020%20TCN%20ISOC%20Grant%20for%20Supernodes

**Comment by benhylau** [comment]
@ryan-fgt do we want to have a meeting next week?

**Comment by ryan-fgt** [comment]
Yeah that works. I have time Monday, Wednesday, or Thursday evening and
have some flexibility during the day.
