### ISSUE TITLE
Investigate ERX-SFP Resiliance

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#42]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

...

## To Do

- [x] check if router loose time on reboot back to EPOC
- [x] check if router loose time on power cycle or loss of power to EPOC
- [x] check if router looses babed on firmware upgrade

**Comment by darkdrgn2k** [comment]
# Check if router looses babed on firmware upgrade
while upgrading form 1.10.7 (from factory) to 1.10.11
ESRX did not loose any of the files that where supposed to help the package stay persistent including the deb package, but the pre-installer did not execute so babeld and all its config was lost.

**Comment by darkdrgn2k** [comment]
>  check if router looses babed on firmware upgrade
Found error in script.  
Upgrade from 1.10.7->1.10.11 babed stays.

**Comment by darkdrgn2k** [comment]
>  check if router loose time on reboot back to EPOC
> check if router loose time on power cycle or loss of power to EPOC

Connected to internet
```
/etc/init.d/ntp stop
ntpdate 0.pool.ntp.org
reboot
```
```
ubnt@ubnt:~$ date
Fri Aug 14 03:37:59 UTC 2020
ubnt@ubnt:~$
```

Hard Boot (power cycle)
```
ubnt@ubnt:~$ date
Fri Aug 14 03:36:50 UTC 2020
ubnt@ubnt:~$
```
