### ISSUE TITLE
Update website to emphasize Toronto Community Network project

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#51]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Publish an update website that features this project with clear ways to participate, and is not confused with previous projects.  

The website has led to a lot of confusion between the many projects that tomesh worked on. Let's try to redesign the website to present things clearly, and emphasize the existing project.

## To Do

Most of the changes will happen on https://github.com/tomeshnet/tomesh.net
 
- [ ] Wireframe new website
- [ ] New logo?
- [ ] Present updated map with supernodes
- [ ] Link to TCN spaces
- [ ] Add mailing list
- [ ] Improve "Get Involved" sections
