### ISSUE TITLE
tomesh project review

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#52]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have an updated and accurate project page on website.

...

## To Do

- [ ] Review existing project
- [ ] Mark projects inactive and add description about them
- [ ] Update website
- [ ] Prioritize Toronto community project
