### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by makeworld-the-better-one** [tomeshnet/toronto-community-network#54]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** N/A
📅 **Due date:** N/A  
🎯 **Success criteria:** A central documentation area has been set up under source/version control and  is visible on the website, at `docs.tomesh.net`.

A place for technical documentation is needed, so that important information doesn't get left behind in issues in this repo. It was determined (in a call on 2020-08-03) that some sort of online book format is preferred, akin to Gitbook.

## To Do

- [x] Decide on preferred online book software
- [x] Pick docs license
- [x] Create a repo and CI pipeline to publish to website

**Comment by makeworld-the-better-one** [comment]
## Book Software
- [Gitbook](https://github.com/GitbookIO/gitbook)
	- Pro: Some people already have experience
	- Con: "the CLI is no longer under active development"
- [HonKit](https://github.com/honkit/honkit)
	- Fork of GitBook, written in Javascript, 1.3k stars
- [mdBook](https://github.com/rust-lang/mdBook)
	- Similar to Gitbook, written in Rust, 4.7k stars

**Comment by benhylau** [comment]
I want to leave some examples of what can go into a "book":
- https://docs.nycmesh.net
- https://handbook.hypha.coop
- https://handbook.enspiral.com

#30 #35 definitely can go in.

**Comment by benhylau** [comment]
Also I'd say this is `high priority` :)

**Comment by makeworld-the-better-one** [comment]
Both things added, thanks.

**Comment by benhylau** [comment]
We are missing something that tells the overall network topology. These are scattered all over a private chat before this project was announced. We need to rebuild that information in this doc. Here's a rough sketch, someone who can draw needs to turn this into something better :)

![tcn-sketch](https://user-images.githubusercontent.com/2261308/89275784-07c93080-d643-11ea-9b7a-25403b079ec6.jpg)

**Comment by makeworld-the-better-one** [comment]
## Re: [Book Software](https://github.com/tomeshnet/toronto-community-network/issues/54#issuecomment-668218882)

Gitbook is unmaintained and will likely add to our tech debt, and so I'm not in favour of using it.

I think that mdBook will be easier to install and set up because you can install a single binary, instead of going through the `npm` process with HonKit. Most the usage of the tool will likely be in CI anyway, but it's still nice for the local dev to be quick and easy.

Does anyone disagree or have thoughts on this? The sooner we pick this tool the sooner we can move on to the next steps.

**Comment by benhylau** [comment]
As long as it can be hosted as a static site and on CI, I don't see any problem. Both mdBook and HonKit look fine to me.

**Comment by darkdrgn2k** [comment]
> We are missing something that tells the overall network topology. 

This is something we are still figuring out. But i agree that this topology needs to be documented

**Comment by darkdrgn2k** [comment]
> I want to leave some examples of what can go into a "book":
few others
https://dweb-camp-2019.github.io/meshnet/ <> https://github.com/dweb-camp-2019/meshnet
https://tomeshnet.github.io/p2p-internet-workshop/ <> https://github.com/tomeshnet/p2p-internet-workshop/

**Comment by makeworld-the-better-one** [comment]
The [toronto-community-network-docs](https://github.com/tomeshnet/toronto-community-network-docs) repo has been created.

Creating the repo reminded, me what license should our documentation be under? The main choice I see is whether to allow commercial use and modification of the docs.
- If no: [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)
- If yes: [CC0](https://creativecommons.org/publicdomain/zero/1.0/) (public domain)

**Comment by darkdrgn2k** [comment]
![image](https://user-images.githubusercontent.com/29005789/89484989-c1bcbb80-d76d-11ea-8897-3f86dd894840.png)
[mesh-definitions.vsdx.zip](https://github.com/tomeshnet/toronto-community-network/files/5032271/mesh-definitions.vsdx.zip)

**Comment by makeworld-the-better-one** [comment]
The CI pipeline has been set up and is working. The documentation is live at https://docs.tomesh.net. I'm going to close this issue, and all further documentation efforts should probably be in #32.
