### ISSUE TITLE
Chat Restructure

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/toronto-community-network#55]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** All to-do items dealt with, chat successfully restructured.

Design --> Communications
Tools --> Operations
Deployment --> Network
Funding --> Governance

- Addresses should remain as aliases

## To Do

- [x] Make the rooms into the other rooms as explained above!
- [x] Detailed room topics for working group rooms
  -  [x] On Element
  -  [x] On Slack
- [x] Update readme with new addresses for each working group's room
- [x] Demote users that should note be admins
  - [x] Identify users 
  - [x] Demote users 
- [x] Fix slack bridge room names

**Comment by darkdrgn2k** [comment]
Please identify users in format @username:tomesh.net

- Communications - !UNOHFZwimTIlFyfeAQ:tomesh.net

- Operations - !skzhIOidAxzdkqKSnU:tomesh.net

- Network - !JHUsRhirGUBIlKXAkI:tomesh.net

- Governance - !ZwHhMVscDeozYOrsVD:tomesh.net

**Comment by hank** [comment]
Please stop tagging me as I have nothing to do with this.
