### ISSUE TITLE
node-list schema and CI

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#57]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Define new schema and validate with CI for list of consumers.

Define https://github.com/tomeshnet/node-list schema based on consumer (who will parse it) needs and ensure CI catches non-conformant json files and prevent merge.

## To Do

- [x] Define schema
- [x] Collect list of consumers (current only map on website, but perhaps a real-time status poll bot, chat bot, or compiled KML assets by CI?)
- [x] Handle images
- [x] Validate CI catches invalid jsons
- [x] Cut new version 0.7 of schema
- ~~Update [json-schema](https://json-schema.org/) spec version to `2019-09` (repo uses `draft-04` from 2013), and make sure it still works with CI~~
	- See two migrations documents: [Draft-04 to Draft-07](https://json-schema.org/draft-07/json-hyper-schema-release-notes.html) and [Draft-07 to 2019-09](https://json-schema.org/draft/2019-09/release-notes.html#hyper-schema-vocabulary)
	- Is there value in this? (edit by @benhylau: no we should not do this, see comment)

**Comment by benhylau** [comment]
I would like some advice on this:

>- Collect list of consumers (current only map on website, but perhaps a real-time status poll bot, chat bot, or compiled KML assets by CI?)

What do y'all think are consumers of the data?

**Comment by darkdrgn2k** [comment]
> What do y'all think are consumers of the data?

In nycmesh all conversations with "do you have a node number" if not goto https://www.nycmesh.net/join

This information goes (automatically?) into a google sheets and that informs their website map. Each entry gets a node number that then is used to discuss.

I think this process needs to be defined before we translate it into json (or other source)

**Comment by makeworld-the-better-one** [comment]
> What do y'all think are consumers of the data?

@benhylau The list you gave (map, bots, KML) covers most things I think. Generation of static maps for promotion and distribution could be another consumer, as I assume the rendering of static maps is a totally separate process than the way the website map works.

**Comment by benhylau** [comment]
Hmm, would be cool if there is a library for:
- coordinates -> kml
- coordinates -> map PNG

Then we can travis ci run them and output assets to github releases on merge.

**Comment by makeworld-the-better-one** [comment]
Yes, that would be great. Potentially there might be existing mapgen tools that work with KML, which could simplify the work. That would be a good thing to look in to.

**Comment by makeworld-the-better-one** [comment]
> Validate CI catches invalid jsons

This is already happening in the node-list repo, isn't it?

**Comment by makeworld-the-better-one** [comment]
> Hmm, would be cool if there is a library for:
> 
> * coordinates -> kml
> * coordinates -> map PNG

I'd be happy to look into this. I've made a separate issue for it, #67.

**Comment by makeworld-the-better-one** [comment]
> - [ ]  Define schema

@benhylau Can you elaborate on what is needed for version 0.7 of the schema?

**Comment by darkdrgn2k** [comment]
I think its premature to try to permute the file while its in flux.

I think there are many datapoints we need to figure out how and were to store first.

**Comment by makeworld-the-better-one** [comment]
Like what? Can we figure them out in this issue?

**Comment by darkdrgn2k** [comment]
i have no idea. there is a plethora of things that need to be figure out that spans multiple disciplines.

From monitoring, to on-boarding, to running services, to tacking the network.

**Comment by darkdrgn2k** [comment]
> Collect list of consumers

what does this mean?

**Comment by makeworld-the-better-one** [comment]
@darkdrgn2k I chimed in about it [above](https://github.com/tomeshnet/toronto-community-network/issues/57#issuecomment-669544946). My understanding was the Ben was asking who would be using or "consuming" the JSON files, what software would be using that data as input. I spun this into #67, to address any software we'd need to write ourselves.

**Comment by makeworld-the-better-one** [comment]
Does it make sense to work on #67 currently, or should I wait until the new schema has been defined so I don't duplicate work?

**Comment by makeworld-the-better-one** [comment]
I have created a draft version of schema v0.7 in [this PR](https://github.com/tomeshnet/node-list/pull/32). Reviews would be helpful.

**Comment by benhylau** [comment]
>See two migrations documents: Draft-04 to Draft-07 and Draft-07 to 2019-09
>Is there value in this?

I actually did a Draft-07 one before, but it turns out it's poorly supported across tools. Our CI validation tool, linked in README, does not support Draft-07 and I have noted this in README. There is little actual value to upgrade. What we have is Draft-07 compatible, but not the other way around.
