### ISSUE TITLE
Supernode deployment prioritizations

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#60]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Decide on a set of roofs we would like to deploy as supernode and estimate budget requirements.

[MAIN TEXT HERE]

## To Do

- [ ] Evaluate Cisco's deployment locations
- [ ] Discuss within @tomeshnet/network-planning-design-and-operations to prioritize deployments strategically
- [ ] Estimate budget for deployment

**Comment by darkdrgn2k** [comment]
Deployment locations
#61,#62  Thorncliff
#63,#64  Cougar
#65 Nisca
#66 Howard

**Comment by benhylau** [comment]
- @tomeshnet/project-operations discussed this with @YurkoWasHere as @tomeshnet/network-planning-design-and-operations we will try to deploy as many as we can, prioritizing coverage
- @TimTor longer-term, we need better tools and processes to sift thru trade-offs in our deployments
- @YurkoWasHere how to evaluate where resources will go
- @TimTor imagine we get good at finding new buildings independently, there will be a lot of nodes to deploy
- @benhylau we don't need a lot of supernodes, they can be future community activities, they should arrive based on need
- @YurkoWasHere in the future, the building itself don't actually get free wifi, it'll be a harder sell
