### ISSUE TITLE
Supernode - Niska

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#65]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**

320 and 310 Niska
Possible P2P to Knaff
Possible P2P to 10 San Romano Way

## To Do

- [ ] Design Super Node
- [ ] Pay for Super Node
- [ ] Deploy Super Node

**Comment by darkdrgn2k** [comment]
Cant do due to politics. Revising other possibilities.
