### ISSUE TITLE
Identification stickers for hardware

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#7]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** 7/22/2020
🎯 **Success criteria:** Stickers ready to be applied to hardware.

...

## To Do

- [x] Get phone number #14
- [x] Get stickers designed (@Shrinks99)
- [x] Get stickers ordered
- [x] Get stickers delivered

**Comment by benhylau** [comment]
@Shrinks99 how do you feel about having no logo for now and perhaps you (and maybe Io) will come up with a new logo, or at least decide on an existing one, but we don't need to put them on the sticker for now. Instead decide on a wordmark and font that we'd use consistently across spaces?

**Comment by Shrinks99** [comment]
@benhylau This is exactly what I was planning to do, wordmark & design will be similar to the proposal doc's styling.

Are we choosing the 75 mm x 50 mm for $86/100 stickers option from [Stickermule](https://www.stickermule.com/ca/products/rectangle-roll-labels)?  Once I have confirmation on this I'll make it today.

**Comment by darkdrgn2k** [comment]
I would suggest keeping them as small as possible.

Our hardware is not that big.

**Comment by Shrinks99** [comment]
![IMG_7262](https://user-images.githubusercontent.com/5672810/87880829-e0c3fb00-c9c2-11ea-8731-cf35d9f102a7.jpg)

Here's the two smallest sizes next to some stuff from my desk for reference.  @darkdrgn2k The 50x25 is pretty much asset tag size, do you think the 75x50 would fit on everything or is it too big?

**Comment by benhylau** [comment]
I would say either that or 50x50, but definitely get at least 200. One deployment is 10 stickers, so we'll run out in no time.

![Screen Shot 2020-07-19 at 7 21 40 PM](https://user-images.githubusercontent.com/2261308/87880848-4204c200-c9f5-11ea-9733-8a0bbf8a58ad.png)

If you can make them nice enough we can dual-use them for marketing, in which case just print 500 of them. If the grant falls thru I'll cover your cost for it. Also, round corners are perhaps harder to peel.

**Comment by darkdrgn2k** [comment]
Ran out of time for first deployment 

Using make-shift labels

![image](https://user-images.githubusercontent.com/29005789/88243949-0e79a000-cc60-11ea-8184-5ce5379f5fd1.png)

**Comment by Shrinks99** [comment]
Asset tags ordered, they will be sent directly to @darkdrgn2k and should arrive on (or before) Friday August 14th.
