### ISSUE TITLE
Clarify scope of Project Operations, roles and responsibilities

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#78]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Communicate to membership the scope, roles and responsibilities of Project Operations. Document this in handbook.

Clarify that the role of Project Operations is like a PMO (Project Management Office), not a organizational/program-wide operations group. If a project is not defined by the Organizational group (with Project Operations), there is no Project Operations responsibility/accountability.

Organizational group should scope out projects, then get Project Operations involved in the project's implementation. For example, a deployment is a project, the documentation work on docs.tomesh.net is a project. This discipline is important so every task that needs doing doesn't just get dumped into Project Operations.

Organizational group should seek advice from Project Operations in formulating project scope and plans.

_Co-draft this at meeting with @TimTor_

## To Do

- [ ] Revisit WG descriptions
- [ ] Draft more detail about how the WG fits within the workflow with other WGs
- [ ] Add this to docs
- [ ] Communicate this clearly to membership
- [ ] Guidance about how this WG functions and ensure we can onboard new members within the WG

**Comment by benhylau** [comment]
A lot of projects "spring up" (e.g. docs) based on needs perceived by members. Project Operations can take a "service role" and help unblock barriers and scope projects, to make them official, establish roles and accountability structure.

**Comment by benhylau** [comment]
A Project is represented by a GitHub Milestone, backed by a Crew. List of Projects:

- Website improvement #52 
- Information management improvement #32 #54 #57
...

_Feel free to edit this list._
