### ISSUE TITLE
Establish learning group within Governance group

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#79]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Establish learning group to build alignment, for one month.

@TimTor suggested we start discussing higher level items as Governance group, and share readings.

## To Do

- [ ] @tomeshnet/organizational-and-program-governance members to review prior arts within this groups mission
  - https://github.com/tomeshnet/documents/tree/master/tomesh_mission/2018
- [ ] Bring one document / paper / discussion point to share with each other

---

## Reading Pool

_Please use the :memo: link to indicate your name once you have completed the reading, and to put your reflections and questions anonymously, which will guide our discussion sessions._

- [x] 1. [Development and management of collective network and cloud computing infrastructures](https://dsg.ac.upc.edu/sites/default/files/dsg/phd_roger.pdf): Chapter 3: Guifi.net - Overview 
(added 2020-08-29) [:memo:](https://hackmd.io/3rGGRcSgSRaAhquF9PkOIg?edit)

- [x] 2. [Community Networks Adapt to New Realities Under COVID: A DWeb Meetup Recap](https://medium.com/decentralized-web/community-networks-adapt-to-new-realities-under-covid-a-dweb-meetup-recap-d9367f74735a): Zenzeleni Networks
(added 2020-08-29) [:memo:](https://hackmd.io/--Su1k0KQKWn7QjyMBOvwg?edit)

- [ ] 3. [Constellations of Trust and Distrust in Internet Governance](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2608414)
(added 2020-08-29) [:memo:](https://hackmd.io/KCegiKWDSmSdjHxMyPnVEw?edit)

- [ ] 4. [The Tragedy of the Commons: How Elinor Ostrom Solved One of Life’s Greatest Dilemmas](https://evonomics.com/tragedy-of-the-commons-elinor-ostrom/)
(added 2020-09-09) [:memo:](https://hackmd.io/BO_Mt-W2S1KPb9nhW2VoXA?edit)

- [ ] https://restofworld.org/2020/the-life-and-death-of-snet-havanas-alternative-internet/

### Backlog

_Add interesting articles here we can triage for future readings._

- http://www.picopeer.net/PPA-en.shtml
- https://guifi.net/en/FONNC
- Development and management of collective network and cloud computing infrastructures: https://dsg.ac.upc.edu/sites/default/files/dsg/phd_roger.pdf
- https://www.ffdn.org/en
- https://ethgasstation.info/blog/quadratic-funding-in-a-nutshell/
- Interview series with M. Bauwens, Mon, 06 Jul 2020 and  Thu, 08 Oct 2020:
    - https://media.blubrry.com/jimruttshow/content.blubrry.com/jimruttshow/JRS-EP63-Michel-Bauwens.mp3
    - https://media.blubrry.com/jimruttshow/content.blubrry.com/jimruttshow/JRS-EP83-Michel-Bauwens.mp3

**Comment by benhylau** [comment]
I have added some resources to the top issue from [this post](https://github.com/tomeshnet/toronto-community-network/issues/75#issuecomment-673647848) as well as a [recent virtual meetup](https://medium.com/decentralized-web/community-networks-adapt-to-new-realities-under-covid-a-dweb-meetup-recap-d9367f74735a).

For this Saturday's meeting, I'd like us to review [Chapter 3: Guifi.net - Overview of Roger's thesis](https://dsg.ac.upc.edu/sites/default/files/dsg/phd_roger.pdf) and watch [the segment on Zenzeleni Networks](https://medium.com/decentralized-web/community-networks-adapt-to-new-realities-under-covid-a-dweb-meetup-recap-d9367f74735a). Of course, you can read/watch all of it, but these are the parts I hope to discuss :)

**Comment by benhylau** [comment]
@ultush @Pedro-on-a-bike @TimTor I have edited the top issue based on how we'd like the learning group to move forward. I expect our first discussion to take place around September 17, and we will set the exact date time at this Saturday's meeting. Please plan to have readings completed before then.

**Comment by benhylau** [comment]
Moved to https://docs.tomesh.net/operations/learning-group.html
