### ISSUE TITLE
Network Organization

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#8]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Be ready to deploy IPs to production network. 

...

## To Do

- [x] Figure out IP assignment #21 
- [x] Figure out Node Naming
- [ ] Where to store IP and Node Information
- [ ] Where to store service information

**Comment by makeworld-the-better-one** [comment]
> - [ ] Figure out IP assignment #21

It'd be nice to have a service where we can enter addresses that have been already been assigned, and then when we're doing an install ask that service for the next available IP address, and it will give one that is guaranteed not to be used by anyone else.
