### ISSUE TITLE
Determine regulating mechanism for Network Bandwidth and Congestion

### ISSUE THREAD

**Issue by Pedro-on-a-bike** [tomeshnet/toronto-community-network#85]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

There is currently no defined mechanism to regulate bandwidth and therefore alleviate congestion on the network. There is also no mechanism to define and discriminate traffic. The network is currently unrestricted and will assume full bandwidth for all users until saturated. 

Moving forward, say if we are going to adopt a model where we suggest a donation to help support the network, are we then going to have a blanket QoS? Or traffic shape all connections to 15Mbps? What happens if one node requires more bandwidth than another? How do we prioritize traffic? In addition, how do we disincentivize users from saturating bandwidth and just leaving YouTube on all day at 4K. Do we then switch to PPPoE and define a tiered model? Or do we use a pay-per-use model to achieve the same behaviour?

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**

[MAIN TEXT HERE]

## To Do

- [ ] Determine the long term plan as to how we will regulate bandwidth on the network. Will it be a self-regulating pay-per-use model, will it be a subscription model for tiered service through PPPoE, a donation model and use QoS to treat all traffic the same?
- [ ] If we use a pay-per-use model, fees collected can still be redirected back to organization to help pay for overhead and infrastructure. A pay-per-use model would be similar to cell phone plans with the desired effect on end user behaviour so they are price conscious of their usage. This could also allow the network to easily grow as it will be self regulating by only requiring each individual to monitor and adjust their behaviour. A primary con is that pay-per-use is generally frowned upon given their abuse in cell phone plans, however fees on this network can be potentially set at fraction of the price to make it affordable.
- [ ] If we use a subscription model for tiered service via PPPoE, we essentially are becoming an WISP. The big issue with this is that it now centralizes all access to the org and increases administration and governance for anyone who wants to join the network. It does however allow for discrimination if one node requires more bandwidth vs another. This can also potentially limit organic growth of the mesh as each new node will need to request access from the central org, as opposed to a pay-per-use model would only need to request access from their neighbor.
- [ ] If we are looking at a donation model and use QoS or blanket traffic shaping for all users, this will be very simple to implement, however it will become an issue if you have say have a community node that doesn't have direct access to a gateway and only has access through another node. If that other node is already limited to a 15Mbps connection, then that secondary node will also be capped at 15Mbps to service all their clients. This model will also not address the issue if different users have different bandwidth needs.

**Comment by Pedro-on-a-bike** [comment]
To add to this, based on other discussions we have had and testing, the simplest solution right now to avoid congestion and make sure bandwidth is available to all members is to add a traffic shaping policy on all CPEs to limit the TX and RX rates to 25Mbps for individual users and adjust as needed and limit the total number of users that have access to a specific Access Point. At this current time, we are using Ubiquiti equipment for all access points and the CPEs require credentials to establish a connection over AirMax and this can be managed through this MAC Address. Since both the network administrations and the end user will need remote access to the CPE, it is probably easiest to this time just to have a terms of use and "honor" system for the time being that all CPEs on Point to Multi Point links will have some sort of traffic shaping policy until we establish a long term plan.
