### ISSUE TITLE
Routing Hardware - OmniTik AC 5 POE

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#90]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Identify limitations and uses of OmniTik

## To Do
- [ ] Research device potential with stock firmware
  - [ ] POE Switch using VLANs back to edge router
  - [ ] Mesh wireless
- [x] Speed test routing (!900 Mbps)
- [ ] Speed test bridge
- [ ] See if there is a switch that can be used instead of bridging for VLANs

:x: Router
- Will not run Babeld

:x: Try to get openwrt working on it
- No stock firmware support "omni_sc" (reported as boot)

**Comment by darkdrgn2k** [comment]
Work Log:

- Received used device from eBay to evaluate. No additional items including mounting bracket.
- Would not respond as expected to factory reset
- [WinBox](https://mikrotik.com/download) Would not connect (invalid password on port 2-5)
- When connected to a switch ports 2-5 would flap
- Managed top "recover" device using [netinstall](https://i.mt.lv/cdn/product_files/OmniTik-series-wg_200152.pdf)
  - **IMPORTANT** When using net install disable ALL other network interfaces first
- Device responded as expected
- Successfully configured as Access Point
- Configured ports as Layer 3  Ports
- Performed iperf3 speed test between two pi, ~900MBps speeds

:heavy_check_mark:  Can power a Ubiq LAP 120
:x: No root shell, only propitiatory CLI interface
:x: No babeld routing protocol
:x: No Ability to side load packages (packages now signed)
:x: No L2TP Tunnels

:question: Possible ability to use OpenWrt Instead.  Very "generic" firmware out there

**Comment by darkdrgn2k** [comment]
Device did not come with any mounting hardware.  Designed and printed a [basic mount](https://www.thingiverse.com/thing:4582855)

![image](https://user-images.githubusercontent.com/29005789/91640883-c54f0580-e9ee-11ea-84d7-3a2fed649eba.png)

![image](https://user-images.githubusercontent.com/29005789/91640887-ca13b980-e9ee-11ea-9750-9348ca588345.png)

Source Files: [MicroTik OmniTik Mount 0.2.zip](https://github.com/tomeshnet/toronto-community-network/files/5145505/MicroTik.OmniTik.Mount.0.2.zip)

**Comment by darkdrgn2k** [comment]
OpenWRT attempt (FAILED)

Instructions at: https://openwrt.org/toh/mikrotik/common
Firmware: [openwrt-19.07.2-ar71xx-mikrotik-rb-nor-flash-16M-ac-initramfs-kernel.bin](https://archive.openwrt.org/releases/19.07.2/targets/ar71xx/mikrotik/openwrt-19.07.2-ar71xx-mikrotik-rb-nor-flash-16M-ac-initramfs-kernel.bin)

Console: 
```
OpenWrt kernel loader for AR7XXX/AR9XXX
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... done!
Starting kernel at 80060000...

[    0.000000] Linux version 4.14.171 (builder@buildhost) (gcc version 7.5.0 (OpenWrt GCC 7.5.0 r10947-65030d81f3)) #0 Thu Feb 27 21:05:12 2020
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] SoC: Qualcomm Atheros QCA9558 ver 1 rev 0
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] random: get_random_bytes called from 0x80527740 with crng_init=0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: no-uart no-nand parts=1 boot_part_size=16777216 gpio=551410219 HZ=360000000 mem=128M kmac=64:D1:54:B2:14:49 board=omni-sc ver=3.41 hw_opt=00294005 boot=1 mlc=11 rootfstype=squashfs noinitrd
[    0.000000] MIPS: no machine found for id 'omni-sc', supported machines:
[    0.000000] id                       name
[    0.000000] Generic                  Generic AR71XX/AR724X/AR913X based board
[    0.000000] 2011G                    (null)
[    0.000000] 2011r5                   (null)
[    0.000000] 2011US                   (null)
[    0.000000] 2011L                    (null)
[    0.000000] 493G                     MikroTik RouterBOARD 493G
[    0.000000] 493                      MikroTik RouterBOARD 493/AH
[    0.000000] 450G                     MikroTik RouterBOARD 450G
[    0.000000] 450                      MikroTik RouterBOARD 450
[    0.000000] 435G                     MikroTik RouterBOARD 435G
[    0.000000] 433U                     MikroTik RouterBOARD 433UAH
[    0.000000] 433                      MikroTik RouterBOARD 433/AH
[    0.000000] 411U                     MikroTik RouterBOARD 411U
[    0.000000] 411                      MikroTik RouterBOARD 411/A/AH
[    0.000000] 751g                     MikroTik RouterBOARD 751G
[    0.000000] 751                      MikroTik RouterBOARD 751
[    0.000000] 750Gr3                   MikroTik RouterBOARD 750GL
[    0.000000] 750i                     MikroTik RouterBOARD 750
[    0.000000] 711Gr100                 (null)
[    0.000000] 922gs                    (null)
[    0.000000] 951HnD                   MikroTik RouterBOARD 951Ui-2HnD
[    0.000000] 951G                     MikroTik RouterBOARD 951G-2HnD
[    0.000000] 931                      (null)
[    0.000000] wapg-sc                  (null)
[    0.000000] map2-hb                  (null)
[    0.000000] cap-hb                   (null)
[    0.000000] wap-lte                  (null)
[    0.000000] wap-hb                   (null)
[    0.000000] lhg                      (null)
[    0.000000] 750-hb                   (null)
[    0.000000] 962                      (null)
[    0.000000] 952-hb                   (null)
[    0.000000] 911L                     (null)
[    0.000000] H951L                    (null)
[    0.000000] map-hb                   (null)
[    0.000000] sxt5n                    MikroTik RouterBOARD SXT Lite5
[    0.000000] sxt2n                    MikroTik RouterBOARD SXT Lite2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 121860K/131072K available (4184K kernel code, 179K rwdata, 520K rodata, 2532K init, 213K bss, 9212K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] Clocks: CPU:720.000MHz, DDR:600.000MHz, AHB:240.000MHz, Ref:40.000MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 5309056796 ns
[    0.000007] sched_clock: 32 bits at 360MHz, resolution 2ns, wraps every 5965232126ns
[    0.008686] Calibrating delay loop... 358.80 BogoMIPS (lpj=1794048)
[    0.075686] pid_max: default: 32768 minimum: 301
[    0.081009] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.088384] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.098148] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.109142] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.116840] NET: Registered protocol family 16
[    0.123040] MIPS: machine is Generic AR71XX/AR724X/AR913X based board
[    0.142701] clocksource: Switched to clocksource MIPS
[    0.149128] NET: Registered protocol family 2
[    0.154736] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.162509] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.169635] TCP: Hash tables configured (established 1024 bind 1024)
[    0.176834] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.183381] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.190562] NET: Registered protocol family 1
[    2.572712] random: fast init done
[    3.107803] Crashlog allocated RAM at address 0x3f00000
[    3.114705] workingset: timestamp_bits=30 max_order=15 bucket_order=0
[    3.125828] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.132322] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    3.247147] io scheduler noop registered
[    3.251519] io scheduler deadline registered (default)
[    3.257584] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    3.266313] console [ttyS0] disabled
[    3.290364] serial8250.0: ttyS0 at MMIO 0x18020000 (irq = 11, base_baud = 2500000) is a 16550A
```

**Comment by darkdrgn2k** [comment]
Workable if VLANs are used and babel runs on another device.

until openwrt works on it this product or babeld is added or routeros. this product is not recommended.

**Comment by darkdrgn2k** [comment]
Posted on https://forum.openwrt.org/t/omnitik-5-poe-ac/82493
