### ISSUE TITLE
Convene co-design sessions with Milosh

### ISSUE THREAD

**Issue by TimTor** [tomeshnet/toronto-community-network#94]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** Monday Nov. 30th
🎯 **Success criteria:**  Toronto Mesh has participated as desired in contributing to Milosh's Service Design project

From Milosh:
My proposal consists of developing several scenarios for the future for Toronto Mesh that  can  be  used  to  explore  possible  strategies  for  expanding  the  network,  ... One approach is to develop these scenarios along a timeline, focusing on specific challenges at each stage of development. For an example, in a first phase, the focus would be on reaching a critical  mass  of  users  and  how  this  might  be  accomplished,  while  later  on,  more  speculative  applications  of  the  network  can  be  explored.  A scenario building process entails several general steps, including:
1. Deciding the scope of the scenario, some general assumptions and drivers – in this case, we  would  decide  on  what  the  stages  are,  the  challenges  or  goals  at  each  stage  are  (attract more tech savvy users), some assumptions and drivers (why they join, how they learn about Tomesh etc.)
2. Bringing  the  drivers  together  into  a  framework  –  in  this  step,  we  would  group  the  previously   generated      drivers   for   each   challenge   and   try   to   generate   potential   approaches 
3. Generating  scenarios  –  this  step  would  include  generating  a  number  of  potential  scenarios or strategies to address the challenges
4. Developing  several  scenarios  in  more  detail –  in  this  step,  we  would  decide  on  which  scenarios to pursue further and develop them more in detail
5. Continuously  evaluating  the  scenarios  and  their  goals  –  this  step  is  meant  to  be  repeated  occasionally,  to  validate  and,  if  necessary,  make  change  to  the  scenarios.  In  our case, it would include reviewing the final scenarios

Depending  on  schedules,  this  can  be  done  in  several  ways.  One  is  to  have  two  to  three  participatory sessions,  where  we  can  address  the  different  steps.  The  first  session  would include steps 1 and 2, the second 3 and 4. A third would serve to verify the final scenarios, but isn’t  strictly  necessary,  as  I  can  share  the  finalized  scenarios  via  email  for  feedback.  If  it  is  not  possible  to  do  several  sessions  together,  I  can  conduct  individual  interviews,  going  through  steps  1-3,  then  either  do  one  participatory  session  for  step  4,  or  do  step  4  independently  and  send the results for feedback.

## To Do

- [x] Schedule collaboration sessions 
- [x] Review Milosh's synthesis - research write-up + Service design prototype
- ~~Evaluate and apply prototype to current objectives~~ (out of scope, will happen over 2021)
- [x] Onboard Milosh
- [ ] Collect resources in [cloud drive](https://cloud.tomesh.net/f/2097) ([public link](https://cloud.tomesh.net/s/b3m23t4ySET5SZW))

**Comment by TimTor** [comment]
Proposed times, based on availability and interest at: https://www.when2meet.com/?9700550-srArD 
Monday, September 7  11:00 – 12:30
Tuesday, September 8  9:00 – 10:30
Thursday, September 10  9:00 – 10:30

**Comment by benhylau** [comment]
@infectedroot record this?
- @benhylau +1
- @ultush neutral
- @TimTor participate less in recorded
  - have a unrecorded part in the end

---

_Move this to handbook._

In general, we don't record our meetings, but for workshops/interviews we should have three options in order of preference:

1. **Public recorded session** with unrecorded discussion in the end (published on "YouTube")
2. **Private recorded session** with unrecorded discussion in the end (stored in our Drive)
3. **Unrecorded session**

This is a choice of the facilitator/presenter of the session. When possible, closed caption via YouTube, etc.

Logistically this will be done via a BBB room, when someone enters there is a disclaimer.

**Comment by benhylau** [comment]
Milosh will upload final assets before end of year.

**Comment by darkdrgn2k** [comment]
One more document to upload..

**Comment by benhylau** [comment]
What doc is still needed? I thought @infectedroot put everything in there?
