### ISSUE TITLE
Service - LetsEncrypt well-known proxy

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#95]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**

By using a WILDCARD (*.tcn.tomesh.net) entry in DNS, we can setup a reverse proxy that would reverse-proxy requests from the internet to node's .well-known directories back to the internal mesh node.

This would create a transparent way for users on the mesh to generate SSL certificates for their nodes

- Node must be registered with our DNS  (so json file of some sort)
- DHCP nodes may be problematic (maybe fix could be integrating DDNS with DHCP Servers?)

## To Do

- [x] Write a proxy config
- [ ] Check if it works
- [ ] Spin up server
- [ ] Cleanup

**Comment by darkdrgn2k** [comment]
Proof of concept - nginx vhost

http://test22.core.tcn.tomesh.net - Generic site that displays 
http://test22.core.tcn.tomesh.net/.well-known/ - proxied request to an internal node 

```
server {
        listen 80;
        listen [::]:80;
        root /var/www/tomesh;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name  ~^(?<subdomain>[^.]+).core.tcn.tomesh.net;
        location /.well-known {
           resolver 100.64.21.12;
           proxy_pass http://$subdomain.core.tcn.tomesh.net;
        }

        location / {
        }
}
```

**Comment by darkdrgn2k** [comment]
LetsEncrypt Test
```
root@Monitor:~# certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel): test@tomesh.net

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server at
https://acme-v02.api.letsencrypt.org/directory
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(A)gree/(C)ancel: a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you be willing to share your email address with the Electronic Frontier
Foundation, a founding partner of the Let's Encrypt project and the non-profit
organization that develops Certbot? We'd like to send you email about our work
encrypting the web, EFF news, campaigns, and ways to support digital freedom.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: n
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel): test22.core.tcn.tomesh.net
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for test22.core.tcn.tomesh.net
Waiting for verification...
Cleaning up challenges
Deploying Certificate to VirtualHost /etc/nginx/sites-enabled/default

Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled
https://test22.core.tcn.tomesh.net

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=test22.core.tcn.tomesh.net
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/test22.core.tcn.tomesh.net/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/test22.core.tcn.tomesh.net/privkey.pem
   Your cert will expire on 2020-12-09. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

root@Monitor:~#
```

**Comment by darkdrgn2k** [comment]
Other refrences for this problem

https://communitynetworks.group/t/anyone-using-https-in-a-cn/286/22

https://hackmd.io/FVrdvDH3RsOQ4ge-7aA4eA
