### ISSUE TITLE
Toronto Public Library Programming and Events

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/toronto-community-network#97]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**
❌ **Blocked by:** 
👈**Depends on:**

Toronto is part of [Cities for Digital Rights](https://citiesfordigitalrights.org) and one of the actions for the Toronto Public Library is to provide public programming on related topics. We are working with TPL on programming and community network development events.

We are in the early phase of brainstorming and exploring possibilities, that may include infrastructural components. I expect to draw on prior experience in [Meshnet 📡 DWeb Camp 2019](https://dweb-camp-2019.github.io/meshnet/), in particular how to grow a community of [Network Stewards](https://dweb-camp-2019.github.io/meshnet/3.2-network-stewards.html) but for the Toronto Community Network, and possibly extend this to digital literacy programming unrelated to network (e.g. building a Jekyll personal blog on the local network). I have noted to TPL that Toronto Mesh hopes to improve diversity and inclusivity of the Torontonians that participate in Toronto Mesh initiatives, and this may be something TPL can help with.

If anyone is interested in participating in these meetings, please let me know.

## To Do

- [ ] Meeting with Fiona
- [ ] Draft objectives

**Comment by benhylau** [comment]
## Milestone: Nov 24

- [ ] Fiona: draft partner agreement with TCN
- [ ] Ben: budget for background checks
- [ ] Yurko: email Fiona to seek IT approval for BBB
- [ ] All: join chat room (to organize work)
- [ ] All: make skeleton of 1.5h presentations (e.g. two google decks):
    - **There are the problem with what exists**
    - **These are the alternatives (prior to let's join TCN)**
    
Details here -> https://hackmd.io/15DzYRh5RZS4bZiqY18VuQ?view#10-NOVEMBER-2020

**Comment by benhylau** [comment]
New roles:
- Yurko: meeting facilitation
- Ben: lead course design
- Rob: project operations
- Marzie: marketing and comm

Next two weeks:
- **Week 1**: everyone to research content, drop relevant links and comments, new slides into the two decks
- **Week 2**: polish content, discuss in chat, ready for discussion at our call

**Comment by infectedroot** [comment]
@maghdaee Fiona has provided a few logos in both PDF and EPS format. Please let me know if these are good for our communications.

[TPL Logos.zip](https://github.com/tomeshnet/toronto-community-network/files/5955369/TPL.Logos.zip)

**Comment by maghdaee** [comment]
Hey @infectedroot 
Is this for promotion material? What kind of promotion material we're thinking? 

and a broader question about the propriety rights in the agreement- Do we have rights to promote the event through our own channel? Do we need approval from TPL?
 
PS. I am on Windows and don't have Adobe/ Corel to open EPS files. So, I only checked the PDG file which looks fine. Still I m unclear what kind of material we're creating but JPEG is easier for me to use generally speaking.

**Comment by benhylau** [comment]
Sorry, some confusion here. The logo is for the TCN project website [here](https://docs.tomesh.net/operations/legal.html#collaborators-and-supporters). I am going to forward to @Shrinks99 to add?

@infectedroot I removed your comment above, bc I am not sure if TPL is okay with having the EPS in public. Another org we have dealt with explicitly wanted that private.

**Comment by Shrinks99** [comment]
TPL is currently using an SVG of their logo on their website. I don't see why using the vectors on ours would be an issue, especially because we were specifically given them to use. They are the best way of displaying this graphic on the web. Happy to convert the EPS to an SVG and implement!

**Comment by Shrinks99** [comment]
Added logo to page, see https://github.com/tomeshnet/toronto-community-network-docs/pull/33 for discussion, there's two things to address before merging.
